# -*- coding: UTF-8 -*-
# Code automatically generated by pycrate_asn1c

from pycrate_asn1rt.utils            import *
from pycrate_asn1rt.err              import *
from pycrate_asn1rt.glob             import make_GLOBAL, GLOBAL
from pycrate_asn1rt.dictobj          import ASN1Dict
from pycrate_asn1rt.refobj           import *
from pycrate_asn1rt.setobj           import *
from pycrate_asn1rt.asnobj_basic     import *
from pycrate_asn1rt.asnobj_str       import *
from pycrate_asn1rt.asnobj_construct import *
from pycrate_asn1rt.asnobj_class     import *
from pycrate_asn1rt.asnobj_ext       import *
from pycrate_asn1rt.init             import init_modules

class EtsiTs103097ExtensionModule:

    _name_  = u'EtsiTs103097ExtensionModule'
    _oid_   = [0, 4, 0, 5, 5, 103097, 2, 1, 1]
    
    _obj_ = [
        u'ExtensionModuleVersion',
        u'Extension',
        u'EXT-TYPE',
        u'ExtId',
        u'EtsiOriginatingHeaderInfoExtension',
        u'EtsiTs103097HeaderInfoExtensionId',
        u'etsiTs102941CrlRequestId',
        u'etsiTs102941DeltaCtlRequestId',
        u'EtsiTs103097HeaderInfoExtensions',
        u'EtsiTs102941CrlRequest',
        u'EtsiTs102941CtlRequest',
        u'EtsiTs102941DeltaCtlRequest',
        ]
    _type_ = [
        u'ExtensionModuleVersion',
        u'Extension',
        u'EXT-TYPE',
        u'ExtId',
        u'EtsiOriginatingHeaderInfoExtension',
        u'EtsiTs103097HeaderInfoExtensionId',
        u'EtsiTs102941CrlRequest',
        u'EtsiTs102941CtlRequest',
        u'EtsiTs102941DeltaCtlRequest',
        ]
    _set_ = [
        u'EtsiTs103097HeaderInfoExtensions',
        ]
    _val_ = [
        u'etsiTs102941CrlRequestId',
        u'etsiTs102941DeltaCtlRequestId',
        ]
    _class_ = [
        u'EXT-TYPE',
        u'EtsiTs103097HeaderInfoExtensions',
        ]
    _param_ = [
        u'Extension',
        ]
    
    #-----< ExtensionModuleVersion >-----#
    ExtensionModuleVersion = INT(name=u'ExtensionModuleVersion', mode=MODE_TYPE)
    ExtensionModuleVersion._const_val = ASN1Set(rv=[1], rr=[], ev=None, er=[])
    
    #-----< Extension >-----#
    Extension = SEQ(name=u'Extension', mode=MODE_TYPE, param=True)
    
    #-----< EXT-TYPE >-----#
    EXT_TYPE = CLASS(name=u'EXT-TYPE', mode=MODE_TYPE)
    _EXT_TYPE_extId = INT(name=u'extId', mode=MODE_VALUE, typeref=ASN1RefType(('EtsiTs103097ExtensionModule', 'ExtId')))
    _EXT_TYPE_ExtContent = OPEN(name=u'ExtContent', mode=MODE_TYPE)
    EXT_TYPE._cont = ASN1Dict([
        (u'extId', _EXT_TYPE_extId),
        (u'ExtContent', _EXT_TYPE_ExtContent),
        ])
    
    #-----< ExtId >-----#
    ExtId = INT(name=u'ExtId', mode=MODE_TYPE)
    ExtId._const_val = ASN1Set(rv=[], rr=[ASN1RangeInt(lb=0, ub=255)], ev=None, er=[])
    
    #-----< EtsiOriginatingHeaderInfoExtension >-----#
    EtsiOriginatingHeaderInfoExtension = SEQ(name=u'EtsiOriginatingHeaderInfoExtension', mode=MODE_TYPE, typeref=ASN1RefType(('EtsiTs103097ExtensionModule', 'Extension')))
    _EtsiOriginatingHeaderInfoExtension_id = INT(name=u'id', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefClassField(('EtsiTs103097ExtensionModule', 'EXT-TYPE'), [u'extId']))
    __EtsiOriginatingHeaderInfoExtension_id_tab = CLASS(name='_tab_EXT-TYPE', mode=MODE_SET, typeref=ASN1RefType(('EtsiTs103097ExtensionModule', 'EXT-TYPE')))
    ___EtsiOriginatingHeaderInfoExtension_id_tab_val_ExtContent_0 = SEQ(name=u'ExtContent', mode=MODE_TYPE, typeref=ASN1RefType(('EtsiTs103097ExtensionModule', 'EtsiTs102941CrlRequest')))
    ___EtsiOriginatingHeaderInfoExtension_id_tab_val_ExtContent_1 = SEQ(name=u'ExtContent', mode=MODE_TYPE, typeref=ASN1RefType(('EtsiTs103097ExtensionModule', 'EtsiTs102941DeltaCtlRequest')))
    __EtsiOriginatingHeaderInfoExtension_id_tab._val = ASN1Set(rv=[dict([(u'ExtContent', ___EtsiOriginatingHeaderInfoExtension_id_tab_val_ExtContent_0), (u'extId', 1)]), dict([(u'ExtContent', ___EtsiOriginatingHeaderInfoExtension_id_tab_val_ExtContent_1), (u'extId', 2)])], rr=[], ev=None, er=[])
    _EtsiOriginatingHeaderInfoExtension_id._const_tab = __EtsiOriginatingHeaderInfoExtension_id_tab
    _EtsiOriginatingHeaderInfoExtension_id._const_tab_at = None
    _EtsiOriginatingHeaderInfoExtension_id._const_tab_id = u'extId'
    _EtsiOriginatingHeaderInfoExtension_content = OPEN(name=u'content', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_EXPLICIT), typeref=ASN1RefClassField(('EtsiTs103097ExtensionModule', 'EXT-TYPE'), [u'ExtContent']))
    _EtsiOriginatingHeaderInfoExtension_content._const_tab = __EtsiOriginatingHeaderInfoExtension_id_tab
    _EtsiOriginatingHeaderInfoExtension_content._const_tab_at = ('..', u'id')
    _EtsiOriginatingHeaderInfoExtension_content._const_tab_id = u'ExtContent'
    EtsiOriginatingHeaderInfoExtension._cont = ASN1Dict([
        (u'id', _EtsiOriginatingHeaderInfoExtension_id),
        (u'content', _EtsiOriginatingHeaderInfoExtension_content),
        ])
    EtsiOriginatingHeaderInfoExtension._ext = None
    
    #-----< EtsiTs103097HeaderInfoExtensionId >-----#
    EtsiTs103097HeaderInfoExtensionId = INT(name=u'EtsiTs103097HeaderInfoExtensionId', mode=MODE_TYPE, typeref=ASN1RefType(('EtsiTs103097ExtensionModule', 'ExtId')))
    
    #-----< etsiTs102941CrlRequestId >-----#
    etsiTs102941CrlRequestId = INT(name=u'etsiTs102941CrlRequestId', mode=MODE_VALUE, typeref=ASN1RefType(('EtsiTs103097ExtensionModule', 'EtsiTs103097HeaderInfoExtensionId')))
    etsiTs102941CrlRequestId._val = 1
    
    #-----< etsiTs102941DeltaCtlRequestId >-----#
    etsiTs102941DeltaCtlRequestId = INT(name=u'etsiTs102941DeltaCtlRequestId', mode=MODE_VALUE, typeref=ASN1RefType(('EtsiTs103097ExtensionModule', 'EtsiTs103097HeaderInfoExtensionId')))
    etsiTs102941DeltaCtlRequestId._val = 2
    
    #-----< EtsiTs103097HeaderInfoExtensions >-----#
    EtsiTs103097HeaderInfoExtensions = CLASS(name=u'EtsiTs103097HeaderInfoExtensions', mode=MODE_SET, typeref=ASN1RefType(('EtsiTs103097ExtensionModule', 'EXT-TYPE')))
    _EtsiTs103097HeaderInfoExtensions_val_ExtContent_0 = SEQ(name=u'ExtContent', mode=MODE_TYPE, typeref=ASN1RefType(('EtsiTs103097ExtensionModule', 'EtsiTs102941CrlRequest')))
    _EtsiTs103097HeaderInfoExtensions_val_ExtContent_1 = SEQ(name=u'ExtContent', mode=MODE_TYPE, typeref=ASN1RefType(('EtsiTs103097ExtensionModule', 'EtsiTs102941DeltaCtlRequest')))
    EtsiTs103097HeaderInfoExtensions._val = ASN1Set(rv=[dict([(u'ExtContent', _EtsiTs103097HeaderInfoExtensions_val_ExtContent_0), (u'extId', 1)]), dict([(u'ExtContent', _EtsiTs103097HeaderInfoExtensions_val_ExtContent_1), (u'extId', 2)])], rr=[], ev=[], er=[])
    
    #-----< EtsiTs102941CrlRequest >-----#
    EtsiTs102941CrlRequest = SEQ(name=u'EtsiTs102941CrlRequest', mode=MODE_TYPE)
    _EtsiTs102941CrlRequest_issuerId = OCT_STR(name=u'issuerId', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('Ieee1609Dot2BaseTypes', 'HashedId8')))
    _EtsiTs102941CrlRequest_lastKnownUpdate = INT(name=u'lastKnownUpdate', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('Ieee1609Dot2BaseTypes', 'Time32')), opt=True)
    EtsiTs102941CrlRequest._cont = ASN1Dict([
        (u'issuerId', _EtsiTs102941CrlRequest_issuerId),
        (u'lastKnownUpdate', _EtsiTs102941CrlRequest_lastKnownUpdate),
        ])
    EtsiTs102941CrlRequest._ext = None
    
    #-----< EtsiTs102941CtlRequest >-----#
    EtsiTs102941CtlRequest = SEQ(name=u'EtsiTs102941CtlRequest', mode=MODE_TYPE)
    _EtsiTs102941CtlRequest_issuerId = OCT_STR(name=u'issuerId', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('Ieee1609Dot2BaseTypes', 'HashedId8')))
    _EtsiTs102941CtlRequest_lastKnownCtlSequence = INT(name=u'lastKnownCtlSequence', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT), opt=True)
    _EtsiTs102941CtlRequest_lastKnownCtlSequence._const_val = ASN1Set(rv=[], rr=[ASN1RangeInt(lb=0, ub=255)], ev=None, er=[])
    EtsiTs102941CtlRequest._cont = ASN1Dict([
        (u'issuerId', _EtsiTs102941CtlRequest_issuerId),
        (u'lastKnownCtlSequence', _EtsiTs102941CtlRequest_lastKnownCtlSequence),
        ])
    EtsiTs102941CtlRequest._ext = None
    
    #-----< EtsiTs102941DeltaCtlRequest >-----#
    EtsiTs102941DeltaCtlRequest = SEQ(name=u'EtsiTs102941DeltaCtlRequest', mode=MODE_TYPE, typeref=ASN1RefType(('EtsiTs103097ExtensionModule', 'EtsiTs102941CtlRequest')))
    
    _all_ = [
        ExtensionModuleVersion,
        _EXT_TYPE_extId,
        _EXT_TYPE_ExtContent,
        EXT_TYPE,
        ExtId,
        __EtsiOriginatingHeaderInfoExtension_id_tab,
        ___EtsiOriginatingHeaderInfoExtension_id_tab_val_ExtContent_0,
        ___EtsiOriginatingHeaderInfoExtension_id_tab_val_ExtContent_1,
        _EtsiOriginatingHeaderInfoExtension_id,
        _EtsiOriginatingHeaderInfoExtension_content,
        EtsiOriginatingHeaderInfoExtension,
        EtsiTs103097HeaderInfoExtensionId,
        etsiTs102941CrlRequestId,
        etsiTs102941DeltaCtlRequestId,
        EtsiTs103097HeaderInfoExtensions,
        _EtsiTs103097HeaderInfoExtensions_val_ExtContent_0,
        _EtsiTs103097HeaderInfoExtensions_val_ExtContent_1,
        _EtsiTs102941CrlRequest_issuerId,
        _EtsiTs102941CrlRequest_lastKnownUpdate,
        EtsiTs102941CrlRequest,
        _EtsiTs102941CtlRequest_issuerId,
        _EtsiTs102941CtlRequest_lastKnownCtlSequence,
        EtsiTs102941CtlRequest,
        EtsiTs102941DeltaCtlRequest,
    ]

class Ieee1609Dot2:

    _name_  = u'Ieee1609Dot2'
    _oid_   = [1, 3, 111, 2, 1609, 2, 1, 1, 2, 3]
    
    _obj_ = [
        u'Ieee1609Dot2Data',
        u'Ieee1609Dot2Content',
        u'SignedData',
        u'ToBeSignedData',
        u'SignedDataPayload',
        u'HashedData',
        u'HeaderInfo',
        u'MissingCrlIdentifier',
        u'PduFunctionalType',
        u'tlsHandshake',
        u'iso21177ExtendedAuth',
        u'ContributedExtensionBlocks',
        u'ContributedExtensionBlock',
        u'IEEE1609DOT2-HEADERINFO-CONTRIBUTED-EXTENSION',
        u'Ieee1609Dot2HeaderInfoContributedExtensions',
        u'HeaderInfoContributorId',
        u'etsiHeaderInfoContributorId',
        u'SignerIdentifier',
        u'EncryptedData',
        u'RecipientInfo',
        u'SequenceOfRecipientInfo',
        u'PreSharedKeyRecipientInfo',
        u'SymmRecipientInfo',
        u'PKRecipientInfo',
        u'EncryptedDataEncryptionKey',
        u'SymmetricCiphertext',
        u'AesCcmCiphertext',
        u'Countersignature',
        u'Certificate',
        u'SequenceOfCertificate',
        u'CertificateBase',
        u'CertificateType',
        u'ImplicitCertificate',
        u'ExplicitCertificate',
        u'IssuerIdentifier',
        u'ToBeSignedCertificate',
        u'CertificateId',
        u'LinkageData',
        u'EndEntityType',
        u'PsidGroupPermissions',
        u'SequenceOfPsidGroupPermissions',
        u'SubjectPermissions',
        u'VerificationKeyIndicator',
        ]
    _type_ = [
        u'Ieee1609Dot2Data',
        u'Ieee1609Dot2Content',
        u'SignedData',
        u'ToBeSignedData',
        u'SignedDataPayload',
        u'HashedData',
        u'HeaderInfo',
        u'MissingCrlIdentifier',
        u'PduFunctionalType',
        u'ContributedExtensionBlocks',
        u'ContributedExtensionBlock',
        u'IEEE1609DOT2-HEADERINFO-CONTRIBUTED-EXTENSION',
        u'HeaderInfoContributorId',
        u'SignerIdentifier',
        u'EncryptedData',
        u'RecipientInfo',
        u'SequenceOfRecipientInfo',
        u'PreSharedKeyRecipientInfo',
        u'SymmRecipientInfo',
        u'PKRecipientInfo',
        u'EncryptedDataEncryptionKey',
        u'SymmetricCiphertext',
        u'AesCcmCiphertext',
        u'Countersignature',
        u'Certificate',
        u'SequenceOfCertificate',
        u'CertificateBase',
        u'CertificateType',
        u'ImplicitCertificate',
        u'ExplicitCertificate',
        u'IssuerIdentifier',
        u'ToBeSignedCertificate',
        u'CertificateId',
        u'LinkageData',
        u'EndEntityType',
        u'PsidGroupPermissions',
        u'SequenceOfPsidGroupPermissions',
        u'SubjectPermissions',
        u'VerificationKeyIndicator',
        ]
    _set_ = [
        u'Ieee1609Dot2HeaderInfoContributedExtensions',
        ]
    _val_ = [
        u'tlsHandshake',
        u'iso21177ExtendedAuth',
        u'etsiHeaderInfoContributorId',
        ]
    _class_ = [
        u'IEEE1609DOT2-HEADERINFO-CONTRIBUTED-EXTENSION',
        u'Ieee1609Dot2HeaderInfoContributedExtensions',
        ]
    _param_ = [
        ]
    
    #-----< Ieee1609Dot2Data >-----#
    Ieee1609Dot2Data = SEQ(name=u'Ieee1609Dot2Data', mode=MODE_TYPE)
    _Ieee1609Dot2Data_protocolVersion = INT(name=u'protocolVersion', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('Ieee1609Dot2BaseTypes', 'Uint8')))
    _Ieee1609Dot2Data_protocolVersion._const_val = ASN1Set(rv=[3], rr=[], ev=None, er=[])
    _Ieee1609Dot2Data_content = CHOICE(name=u'content', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_EXPLICIT), typeref=ASN1RefType(('Ieee1609Dot2', 'Ieee1609Dot2Content')))
    Ieee1609Dot2Data._cont = ASN1Dict([
        (u'protocolVersion', _Ieee1609Dot2Data_protocolVersion),
        (u'content', _Ieee1609Dot2Data_content),
        ])
    Ieee1609Dot2Data._ext = None
    
    #-----< Ieee1609Dot2Content >-----#
    Ieee1609Dot2Content = CHOICE(name=u'Ieee1609Dot2Content', mode=MODE_TYPE)
    _Ieee1609Dot2Content_unsecuredData = OCT_STR(name=u'unsecuredData', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('Ieee1609Dot2BaseTypes', 'Opaque')))
    _Ieee1609Dot2Content_signedData = SEQ(name=u'signedData', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('Ieee1609Dot2', 'SignedData')))
    _Ieee1609Dot2Content_encryptedData = SEQ(name=u'encryptedData', mode=MODE_TYPE, tag=(2, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('Ieee1609Dot2', 'EncryptedData')))
    _Ieee1609Dot2Content_signedCertificateRequest = OCT_STR(name=u'signedCertificateRequest', mode=MODE_TYPE, tag=(3, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('Ieee1609Dot2BaseTypes', 'Opaque')))
    Ieee1609Dot2Content._cont = ASN1Dict([
        (u'unsecuredData', _Ieee1609Dot2Content_unsecuredData),
        (u'signedData', _Ieee1609Dot2Content_signedData),
        (u'encryptedData', _Ieee1609Dot2Content_encryptedData),
        (u'signedCertificateRequest', _Ieee1609Dot2Content_signedCertificateRequest),
        ])
    Ieee1609Dot2Content._ext = []
    
    #-----< SignedData >-----#
    SignedData = SEQ(name=u'SignedData', mode=MODE_TYPE)
    _SignedData_hashId = ENUM(name=u'hashId', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('Ieee1609Dot2BaseTypes', 'HashAlgorithm')))
    _SignedData_tbsData = SEQ(name=u'tbsData', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('Ieee1609Dot2', 'ToBeSignedData')))
    _SignedData_signer = CHOICE(name=u'signer', mode=MODE_TYPE, tag=(2, TAG_CONTEXT_SPEC, TAG_EXPLICIT), typeref=ASN1RefType(('Ieee1609Dot2', 'SignerIdentifier')))
    _SignedData_signature = CHOICE(name=u'signature', mode=MODE_TYPE, tag=(3, TAG_CONTEXT_SPEC, TAG_EXPLICIT), typeref=ASN1RefType(('Ieee1609Dot2BaseTypes', 'Signature')))
    SignedData._cont = ASN1Dict([
        (u'hashId', _SignedData_hashId),
        (u'tbsData', _SignedData_tbsData),
        (u'signer', _SignedData_signer),
        (u'signature', _SignedData_signature),
        ])
    SignedData._ext = None
    
    #-----< ToBeSignedData >-----#
    ToBeSignedData = SEQ(name=u'ToBeSignedData', mode=MODE_TYPE)
    _ToBeSignedData_payload = SEQ(name=u'payload', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('Ieee1609Dot2', 'SignedDataPayload')))
    _ToBeSignedData_headerInfo = SEQ(name=u'headerInfo', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('Ieee1609Dot2', 'HeaderInfo')))
    ToBeSignedData._cont = ASN1Dict([
        (u'payload', _ToBeSignedData_payload),
        (u'headerInfo', _ToBeSignedData_headerInfo),
        ])
    ToBeSignedData._ext = None
    
    #-----< SignedDataPayload >-----#
    SignedDataPayload = SEQ(name=u'SignedDataPayload', mode=MODE_TYPE)
    _SignedDataPayload_data = SEQ(name=u'data', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('Ieee1609Dot2', 'Ieee1609Dot2Data')), opt=True)
    _SignedDataPayload_extDataHash = CHOICE(name=u'extDataHash', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_EXPLICIT), typeref=ASN1RefType(('Ieee1609Dot2', 'HashedData')), opt=True)
    SignedDataPayload._cont = ASN1Dict([
        (u'data', _SignedDataPayload_data),
        (u'extDataHash', _SignedDataPayload_extDataHash),
        ])
    SignedDataPayload._ext = []
    
    #-----< HashedData >-----#
    HashedData = CHOICE(name=u'HashedData', mode=MODE_TYPE)
    _HashedData_sha256HashedData = OCT_STR(name=u'sha256HashedData', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _HashedData_sha256HashedData._const_sz = ASN1Set(rv=[32], rr=[], ev=None, er=[])
    _HashedData_sha384HashedData = OCT_STR(name=u'sha384HashedData', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _HashedData_sha384HashedData._const_sz = ASN1Set(rv=[48], rr=[], ev=None, er=[])
    _HashedData_reserved = OCT_STR(name=u'reserved', mode=MODE_TYPE, tag=(2, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _HashedData_reserved._const_sz = ASN1Set(rv=[32], rr=[], ev=None, er=[])
    HashedData._cont = ASN1Dict([
        (u'sha256HashedData', _HashedData_sha256HashedData),
        (u'sha384HashedData', _HashedData_sha384HashedData),
        (u'reserved', _HashedData_reserved),
        ])
    HashedData._ext = [u'sha384HashedData', u'reserved']
    
    #-----< HeaderInfo >-----#
    HeaderInfo = SEQ(name=u'HeaderInfo', mode=MODE_TYPE)
    _HeaderInfo_psid = INT(name=u'psid', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('Ieee1609Dot2BaseTypes', 'Psid')))
    _HeaderInfo_generationTime = INT(name=u'generationTime', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('Ieee1609Dot2BaseTypes', 'Time64')), opt=True)
    _HeaderInfo_expiryTime = INT(name=u'expiryTime', mode=MODE_TYPE, tag=(2, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('Ieee1609Dot2BaseTypes', 'Time64')), opt=True)
    _HeaderInfo_generationLocation = SEQ(name=u'generationLocation', mode=MODE_TYPE, tag=(3, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('Ieee1609Dot2BaseTypes', 'ThreeDLocation')), opt=True)
    _HeaderInfo_p2pcdLearningRequest = OCT_STR(name=u'p2pcdLearningRequest', mode=MODE_TYPE, tag=(4, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('Ieee1609Dot2BaseTypes', 'HashedId3')), opt=True)
    _HeaderInfo_missingCrlIdentifier = SEQ(name=u'missingCrlIdentifier', mode=MODE_TYPE, tag=(5, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('Ieee1609Dot2', 'MissingCrlIdentifier')), opt=True)
    _HeaderInfo_encryptionKey = CHOICE(name=u'encryptionKey', mode=MODE_TYPE, tag=(6, TAG_CONTEXT_SPEC, TAG_EXPLICIT), typeref=ASN1RefType(('Ieee1609Dot2BaseTypes', 'EncryptionKey')), opt=True)
    _HeaderInfo_inlineP2pcdRequest = SEQ_OF(name=u'inlineP2pcdRequest', mode=MODE_TYPE, tag=(7, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('Ieee1609Dot2BaseTypes', 'SequenceOfHashedId3')), opt=True)
    _HeaderInfo_requestedCertificate = SEQ(name=u'requestedCertificate', mode=MODE_TYPE, tag=(8, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('Ieee1609Dot2', 'Certificate')), opt=True)
    _HeaderInfo_pduFunctionalType = INT(name=u'pduFunctionalType', mode=MODE_TYPE, tag=(9, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('Ieee1609Dot2', 'PduFunctionalType')), opt=True)
    _HeaderInfo_contributedExtensions = SEQ_OF(name=u'contributedExtensions', mode=MODE_TYPE, tag=(10, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('Ieee1609Dot2', 'ContributedExtensionBlocks')), opt=True)
    HeaderInfo._cont = ASN1Dict([
        (u'psid', _HeaderInfo_psid),
        (u'generationTime', _HeaderInfo_generationTime),
        (u'expiryTime', _HeaderInfo_expiryTime),
        (u'generationLocation', _HeaderInfo_generationLocation),
        (u'p2pcdLearningRequest', _HeaderInfo_p2pcdLearningRequest),
        (u'missingCrlIdentifier', _HeaderInfo_missingCrlIdentifier),
        (u'encryptionKey', _HeaderInfo_encryptionKey),
        (u'inlineP2pcdRequest', _HeaderInfo_inlineP2pcdRequest),
        (u'requestedCertificate', _HeaderInfo_requestedCertificate),
        (u'pduFunctionalType', _HeaderInfo_pduFunctionalType),
        (u'contributedExtensions', _HeaderInfo_contributedExtensions),
        ])
    HeaderInfo._ext = [u'inlineP2pcdRequest', u'requestedCertificate', u'pduFunctionalType', u'contributedExtensions']
    
    #-----< MissingCrlIdentifier >-----#
    MissingCrlIdentifier = SEQ(name=u'MissingCrlIdentifier', mode=MODE_TYPE)
    _MissingCrlIdentifier_cracaId = OCT_STR(name=u'cracaId', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('Ieee1609Dot2BaseTypes', 'HashedId3')))
    _MissingCrlIdentifier_crlSeries = INT(name=u'crlSeries', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('Ieee1609Dot2BaseTypes', 'CrlSeries')))
    MissingCrlIdentifier._cont = ASN1Dict([
        (u'cracaId', _MissingCrlIdentifier_cracaId),
        (u'crlSeries', _MissingCrlIdentifier_crlSeries),
        ])
    MissingCrlIdentifier._ext = []
    
    #-----< PduFunctionalType >-----#
    PduFunctionalType = INT(name=u'PduFunctionalType', mode=MODE_TYPE)
    PduFunctionalType._const_val = ASN1Set(rv=[], rr=[ASN1RangeInt(lb=0, ub=255)], ev=None, er=[])
    
    #-----< tlsHandshake >-----#
    tlsHandshake = INT(name=u'tlsHandshake', mode=MODE_VALUE, typeref=ASN1RefType(('Ieee1609Dot2', 'PduFunctionalType')))
    tlsHandshake._val = 1
    
    #-----< iso21177ExtendedAuth >-----#
    iso21177ExtendedAuth = INT(name=u'iso21177ExtendedAuth', mode=MODE_VALUE, typeref=ASN1RefType(('Ieee1609Dot2', 'PduFunctionalType')))
    iso21177ExtendedAuth._val = 2
    
    #-----< ContributedExtensionBlocks >-----#
    ContributedExtensionBlocks = SEQ_OF(name=u'ContributedExtensionBlocks', mode=MODE_TYPE)
    _ContributedExtensionBlocks__item_ = SEQ(name='_item_', mode=MODE_TYPE, typeref=ASN1RefType(('Ieee1609Dot2', 'ContributedExtensionBlock')))
    ContributedExtensionBlocks._cont = _ContributedExtensionBlocks__item_
    ContributedExtensionBlocks._const_sz = ASN1Set(rv=[], rr=[ASN1RangeInt(lb=1, ub=None)], ev=None, er=[])
    
    #-----< ContributedExtensionBlock >-----#
    ContributedExtensionBlock = SEQ(name=u'ContributedExtensionBlock', mode=MODE_TYPE)
    _ContributedExtensionBlock_contributorId = INT(name=u'contributorId', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefClassField(('Ieee1609Dot2', 'IEEE1609DOT2-HEADERINFO-CONTRIBUTED-EXTENSION'), [u'id']))
    __ContributedExtensionBlock_contributorId_tab = CLASS(name='_tab_IEEE1609DOT2-HEADERINFO-CONTRIBUTED-EXTENSION', mode=MODE_SET, typeref=ASN1RefType(('Ieee1609Dot2', 'IEEE1609DOT2-HEADERINFO-CONTRIBUTED-EXTENSION')))
    ___ContributedExtensionBlock_contributorId_tab_val_Extn_0 = SEQ(name=u'Extn', mode=MODE_TYPE, typeref=ASN1RefType(('EtsiTs103097ExtensionModule', 'EtsiOriginatingHeaderInfoExtension')))
    __ContributedExtensionBlock_contributorId_tab._val = ASN1Set(rv=[dict([(u'Extn', ___ContributedExtensionBlock_contributorId_tab_val_Extn_0), (u'id', 2)])], rr=[], ev=None, er=[])
    _ContributedExtensionBlock_contributorId._const_tab = __ContributedExtensionBlock_contributorId_tab
    _ContributedExtensionBlock_contributorId._const_tab_at = None
    _ContributedExtensionBlock_contributorId._const_tab_id = u'id'
    _ContributedExtensionBlock_extns = SEQ_OF(name=u'extns', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    __ContributedExtensionBlock_extns__item_ = OPEN(name='_item_', mode=MODE_TYPE, typeref=ASN1RefClassField(('Ieee1609Dot2', 'IEEE1609DOT2-HEADERINFO-CONTRIBUTED-EXTENSION'), [u'Extn']))
    __ContributedExtensionBlock_extns__item_._const_tab = __ContributedExtensionBlock_contributorId_tab
    __ContributedExtensionBlock_extns__item_._const_tab_at = ('..', '..', u'contributorId')
    __ContributedExtensionBlock_extns__item_._const_tab_id = u'Extn'
    _ContributedExtensionBlock_extns._cont = __ContributedExtensionBlock_extns__item_
    _ContributedExtensionBlock_extns._const_sz = ASN1Set(rv=[], rr=[ASN1RangeInt(lb=1, ub=None)], ev=None, er=[])
    ContributedExtensionBlock._cont = ASN1Dict([
        (u'contributorId', _ContributedExtensionBlock_contributorId),
        (u'extns', _ContributedExtensionBlock_extns),
        ])
    ContributedExtensionBlock._ext = None
    
    #-----< IEEE1609DOT2-HEADERINFO-CONTRIBUTED-EXTENSION >-----#
    IEEE1609DOT2_HEADERINFO_CONTRIBUTED_EXTENSION = CLASS(name=u'IEEE1609DOT2-HEADERINFO-CONTRIBUTED-EXTENSION', mode=MODE_TYPE)
    _IEEE1609DOT2_HEADERINFO_CONTRIBUTED_EXTENSION_id = INT(name=u'id', mode=MODE_VALUE, typeref=ASN1RefType(('Ieee1609Dot2', 'HeaderInfoContributorId')), uniq=True)
    _IEEE1609DOT2_HEADERINFO_CONTRIBUTED_EXTENSION_Extn = OPEN(name=u'Extn', mode=MODE_TYPE)
    IEEE1609DOT2_HEADERINFO_CONTRIBUTED_EXTENSION._cont = ASN1Dict([
        (u'id', _IEEE1609DOT2_HEADERINFO_CONTRIBUTED_EXTENSION_id),
        (u'Extn', _IEEE1609DOT2_HEADERINFO_CONTRIBUTED_EXTENSION_Extn),
        ])
    
    #-----< Ieee1609Dot2HeaderInfoContributedExtensions >-----#
    Ieee1609Dot2HeaderInfoContributedExtensions = CLASS(name=u'Ieee1609Dot2HeaderInfoContributedExtensions', mode=MODE_SET, typeref=ASN1RefType(('Ieee1609Dot2', 'IEEE1609DOT2-HEADERINFO-CONTRIBUTED-EXTENSION')))
    _Ieee1609Dot2HeaderInfoContributedExtensions_val_Extn_0 = SEQ(name=u'Extn', mode=MODE_TYPE, typeref=ASN1RefType(('EtsiTs103097ExtensionModule', 'EtsiOriginatingHeaderInfoExtension')))
    Ieee1609Dot2HeaderInfoContributedExtensions._val = ASN1Set(rv=[dict([(u'Extn', _Ieee1609Dot2HeaderInfoContributedExtensions_val_Extn_0), (u'id', 2)])], rr=[], ev=[], er=[])
    
    #-----< HeaderInfoContributorId >-----#
    HeaderInfoContributorId = INT(name=u'HeaderInfoContributorId', mode=MODE_TYPE)
    HeaderInfoContributorId._const_val = ASN1Set(rv=[], rr=[ASN1RangeInt(lb=0, ub=255)], ev=None, er=[])
    
    #-----< etsiHeaderInfoContributorId >-----#
    etsiHeaderInfoContributorId = INT(name=u'etsiHeaderInfoContributorId', mode=MODE_VALUE, typeref=ASN1RefType(('Ieee1609Dot2', 'HeaderInfoContributorId')))
    etsiHeaderInfoContributorId._val = 2
    
    #-----< SignerIdentifier >-----#
    SignerIdentifier = CHOICE(name=u'SignerIdentifier', mode=MODE_TYPE)
    _SignerIdentifier_digest = OCT_STR(name=u'digest', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('Ieee1609Dot2BaseTypes', 'HashedId8')))
    _SignerIdentifier_certificate = SEQ_OF(name=u'certificate', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('Ieee1609Dot2', 'SequenceOfCertificate')))
    _SignerIdentifier_self = NULL(name=u'self', mode=MODE_TYPE, tag=(2, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    SignerIdentifier._cont = ASN1Dict([
        (u'digest', _SignerIdentifier_digest),
        (u'certificate', _SignerIdentifier_certificate),
        (u'self', _SignerIdentifier_self),
        ])
    SignerIdentifier._ext = []
    
    #-----< EncryptedData >-----#
    EncryptedData = SEQ(name=u'EncryptedData', mode=MODE_TYPE)
    _EncryptedData_recipients = SEQ_OF(name=u'recipients', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('Ieee1609Dot2', 'SequenceOfRecipientInfo')))
    _EncryptedData_ciphertext = CHOICE(name=u'ciphertext', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_EXPLICIT), typeref=ASN1RefType(('Ieee1609Dot2', 'SymmetricCiphertext')))
    EncryptedData._cont = ASN1Dict([
        (u'recipients', _EncryptedData_recipients),
        (u'ciphertext', _EncryptedData_ciphertext),
        ])
    EncryptedData._ext = None
    
    #-----< RecipientInfo >-----#
    RecipientInfo = CHOICE(name=u'RecipientInfo', mode=MODE_TYPE)
    _RecipientInfo_pskRecipInfo = OCT_STR(name=u'pskRecipInfo', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('Ieee1609Dot2', 'PreSharedKeyRecipientInfo')))
    _RecipientInfo_symmRecipInfo = SEQ(name=u'symmRecipInfo', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('Ieee1609Dot2', 'SymmRecipientInfo')))
    _RecipientInfo_certRecipInfo = SEQ(name=u'certRecipInfo', mode=MODE_TYPE, tag=(2, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('Ieee1609Dot2', 'PKRecipientInfo')))
    _RecipientInfo_signedDataRecipInfo = SEQ(name=u'signedDataRecipInfo', mode=MODE_TYPE, tag=(3, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('Ieee1609Dot2', 'PKRecipientInfo')))
    _RecipientInfo_rekRecipInfo = SEQ(name=u'rekRecipInfo', mode=MODE_TYPE, tag=(4, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('Ieee1609Dot2', 'PKRecipientInfo')))
    RecipientInfo._cont = ASN1Dict([
        (u'pskRecipInfo', _RecipientInfo_pskRecipInfo),
        (u'symmRecipInfo', _RecipientInfo_symmRecipInfo),
        (u'certRecipInfo', _RecipientInfo_certRecipInfo),
        (u'signedDataRecipInfo', _RecipientInfo_signedDataRecipInfo),
        (u'rekRecipInfo', _RecipientInfo_rekRecipInfo),
        ])
    RecipientInfo._ext = None
    
    #-----< SequenceOfRecipientInfo >-----#
    SequenceOfRecipientInfo = SEQ_OF(name=u'SequenceOfRecipientInfo', mode=MODE_TYPE)
    _SequenceOfRecipientInfo__item_ = CHOICE(name='_item_', mode=MODE_TYPE, typeref=ASN1RefType(('Ieee1609Dot2', 'RecipientInfo')))
    SequenceOfRecipientInfo._cont = _SequenceOfRecipientInfo__item_
    
    #-----< PreSharedKeyRecipientInfo >-----#
    PreSharedKeyRecipientInfo = OCT_STR(name=u'PreSharedKeyRecipientInfo', mode=MODE_TYPE, typeref=ASN1RefType(('Ieee1609Dot2BaseTypes', 'HashedId8')))
    
    #-----< SymmRecipientInfo >-----#
    SymmRecipientInfo = SEQ(name=u'SymmRecipientInfo', mode=MODE_TYPE)
    _SymmRecipientInfo_recipientId = OCT_STR(name=u'recipientId', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('Ieee1609Dot2BaseTypes', 'HashedId8')))
    _SymmRecipientInfo_encKey = CHOICE(name=u'encKey', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_EXPLICIT), typeref=ASN1RefType(('Ieee1609Dot2', 'SymmetricCiphertext')))
    SymmRecipientInfo._cont = ASN1Dict([
        (u'recipientId', _SymmRecipientInfo_recipientId),
        (u'encKey', _SymmRecipientInfo_encKey),
        ])
    SymmRecipientInfo._ext = None
    
    #-----< PKRecipientInfo >-----#
    PKRecipientInfo = SEQ(name=u'PKRecipientInfo', mode=MODE_TYPE)
    _PKRecipientInfo_recipientId = OCT_STR(name=u'recipientId', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('Ieee1609Dot2BaseTypes', 'HashedId8')))
    _PKRecipientInfo_encKey = CHOICE(name=u'encKey', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_EXPLICIT), typeref=ASN1RefType(('Ieee1609Dot2', 'EncryptedDataEncryptionKey')))
    PKRecipientInfo._cont = ASN1Dict([
        (u'recipientId', _PKRecipientInfo_recipientId),
        (u'encKey', _PKRecipientInfo_encKey),
        ])
    PKRecipientInfo._ext = None
    
    #-----< EncryptedDataEncryptionKey >-----#
    EncryptedDataEncryptionKey = CHOICE(name=u'EncryptedDataEncryptionKey', mode=MODE_TYPE)
    _EncryptedDataEncryptionKey_eciesNistP256 = SEQ(name=u'eciesNistP256', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('Ieee1609Dot2BaseTypes', 'EciesP256EncryptedKey')))
    _EncryptedDataEncryptionKey_eciesBrainpoolP256r1 = SEQ(name=u'eciesBrainpoolP256r1', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('Ieee1609Dot2BaseTypes', 'EciesP256EncryptedKey')))
    EncryptedDataEncryptionKey._cont = ASN1Dict([
        (u'eciesNistP256', _EncryptedDataEncryptionKey_eciesNistP256),
        (u'eciesBrainpoolP256r1', _EncryptedDataEncryptionKey_eciesBrainpoolP256r1),
        ])
    EncryptedDataEncryptionKey._ext = []
    
    #-----< SymmetricCiphertext >-----#
    SymmetricCiphertext = CHOICE(name=u'SymmetricCiphertext', mode=MODE_TYPE)
    _SymmetricCiphertext_aes128ccm = SEQ(name=u'aes128ccm', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('Ieee1609Dot2', 'AesCcmCiphertext')))
    SymmetricCiphertext._cont = ASN1Dict([
        (u'aes128ccm', _SymmetricCiphertext_aes128ccm),
        ])
    SymmetricCiphertext._ext = []
    
    #-----< AesCcmCiphertext >-----#
    AesCcmCiphertext = SEQ(name=u'AesCcmCiphertext', mode=MODE_TYPE)
    _AesCcmCiphertext_nonce = OCT_STR(name=u'nonce', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _AesCcmCiphertext_nonce._const_sz = ASN1Set(rv=[12], rr=[], ev=None, er=[])
    _AesCcmCiphertext_ccmCiphertext = OCT_STR(name=u'ccmCiphertext', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('Ieee1609Dot2BaseTypes', 'Opaque')))
    AesCcmCiphertext._cont = ASN1Dict([
        (u'nonce', _AesCcmCiphertext_nonce),
        (u'ccmCiphertext', _AesCcmCiphertext_ccmCiphertext),
        ])
    AesCcmCiphertext._ext = None
    
    #-----< Countersignature >-----#
    Countersignature = SEQ(name=u'Countersignature', mode=MODE_TYPE, typeref=ASN1RefType(('Ieee1609Dot2', 'Ieee1609Dot2Data')))
    
    #-----< Certificate >-----#
    Certificate = SEQ(name=u'Certificate', mode=MODE_TYPE, typeref=ASN1RefType(('Ieee1609Dot2', 'CertificateBase')))
    Certificate._const_val = ASN1Set(rv=[], rr=[], ev=None, er=[])
    
    #-----< SequenceOfCertificate >-----#
    SequenceOfCertificate = SEQ_OF(name=u'SequenceOfCertificate', mode=MODE_TYPE)
    _SequenceOfCertificate__item_ = SEQ(name='_item_', mode=MODE_TYPE, typeref=ASN1RefType(('Ieee1609Dot2', 'Certificate')))
    SequenceOfCertificate._cont = _SequenceOfCertificate__item_
    
    #-----< CertificateBase >-----#
    CertificateBase = SEQ(name=u'CertificateBase', mode=MODE_TYPE)
    _CertificateBase_version = INT(name=u'version', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('Ieee1609Dot2BaseTypes', 'Uint8')))
    _CertificateBase_version._const_val = ASN1Set(rv=[3], rr=[], ev=None, er=[])
    _CertificateBase_type = ENUM(name=u'type', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('Ieee1609Dot2', 'CertificateType')))
    _CertificateBase_issuer = CHOICE(name=u'issuer', mode=MODE_TYPE, tag=(2, TAG_CONTEXT_SPEC, TAG_EXPLICIT), typeref=ASN1RefType(('Ieee1609Dot2', 'IssuerIdentifier')))
    _CertificateBase_toBeSigned = SEQ(name=u'toBeSigned', mode=MODE_TYPE, tag=(3, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('Ieee1609Dot2', 'ToBeSignedCertificate')))
    _CertificateBase_signature = CHOICE(name=u'signature', mode=MODE_TYPE, tag=(4, TAG_CONTEXT_SPEC, TAG_EXPLICIT), typeref=ASN1RefType(('Ieee1609Dot2BaseTypes', 'Signature')), opt=True)
    CertificateBase._cont = ASN1Dict([
        (u'version', _CertificateBase_version),
        (u'type', _CertificateBase_type),
        (u'issuer', _CertificateBase_issuer),
        (u'toBeSigned', _CertificateBase_toBeSigned),
        (u'signature', _CertificateBase_signature),
        ])
    CertificateBase._ext = None
    
    #-----< CertificateType >-----#
    CertificateType = ENUM(name=u'CertificateType', mode=MODE_TYPE)
    CertificateType._cont = ASN1Dict([(u'explicit', 0), (u'implicit', 1)])
    CertificateType._ext = []
    
    #-----< ImplicitCertificate >-----#
    ImplicitCertificate = SEQ(name=u'ImplicitCertificate', mode=MODE_TYPE, typeref=ASN1RefType(('Ieee1609Dot2', 'CertificateBase')))
    
    #-----< ExplicitCertificate >-----#
    ExplicitCertificate = SEQ(name=u'ExplicitCertificate', mode=MODE_TYPE, typeref=ASN1RefType(('Ieee1609Dot2', 'CertificateBase')))
    
    #-----< IssuerIdentifier >-----#
    IssuerIdentifier = CHOICE(name=u'IssuerIdentifier', mode=MODE_TYPE)
    _IssuerIdentifier_sha256AndDigest = OCT_STR(name=u'sha256AndDigest', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('Ieee1609Dot2BaseTypes', 'HashedId8')))
    _IssuerIdentifier_self = ENUM(name=u'self', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('Ieee1609Dot2BaseTypes', 'HashAlgorithm')))
    _IssuerIdentifier_sha384AndDigest = OCT_STR(name=u'sha384AndDigest', mode=MODE_TYPE, tag=(2, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('Ieee1609Dot2BaseTypes', 'HashedId8')))
    IssuerIdentifier._cont = ASN1Dict([
        (u'sha256AndDigest', _IssuerIdentifier_sha256AndDigest),
        (u'self', _IssuerIdentifier_self),
        (u'sha384AndDigest', _IssuerIdentifier_sha384AndDigest),
        ])
    IssuerIdentifier._ext = [u'sha384AndDigest']
    
    #-----< ToBeSignedCertificate >-----#
    ToBeSignedCertificate = SEQ(name=u'ToBeSignedCertificate', mode=MODE_TYPE)
    _ToBeSignedCertificate_id = CHOICE(name=u'id', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_EXPLICIT), typeref=ASN1RefType(('Ieee1609Dot2', 'CertificateId')))
    _ToBeSignedCertificate_cracaId = OCT_STR(name=u'cracaId', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('Ieee1609Dot2BaseTypes', 'HashedId3')))
    _ToBeSignedCertificate_crlSeries = INT(name=u'crlSeries', mode=MODE_TYPE, tag=(2, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('Ieee1609Dot2BaseTypes', 'CrlSeries')))
    _ToBeSignedCertificate_validityPeriod = SEQ(name=u'validityPeriod', mode=MODE_TYPE, tag=(3, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('Ieee1609Dot2BaseTypes', 'ValidityPeriod')))
    _ToBeSignedCertificate_region = CHOICE(name=u'region', mode=MODE_TYPE, tag=(4, TAG_CONTEXT_SPEC, TAG_EXPLICIT), typeref=ASN1RefType(('Ieee1609Dot2BaseTypes', 'GeographicRegion')), opt=True)
    _ToBeSignedCertificate_assuranceLevel = OCT_STR(name=u'assuranceLevel', mode=MODE_TYPE, tag=(5, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('Ieee1609Dot2BaseTypes', 'SubjectAssurance')), opt=True)
    _ToBeSignedCertificate_appPermissions = SEQ_OF(name=u'appPermissions', mode=MODE_TYPE, tag=(6, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('Ieee1609Dot2BaseTypes', 'SequenceOfPsidSsp')), opt=True)
    _ToBeSignedCertificate_certIssuePermissions = SEQ_OF(name=u'certIssuePermissions', mode=MODE_TYPE, tag=(7, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('Ieee1609Dot2', 'SequenceOfPsidGroupPermissions')), opt=True)
    _ToBeSignedCertificate_certRequestPermissions = SEQ_OF(name=u'certRequestPermissions', mode=MODE_TYPE, tag=(8, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('Ieee1609Dot2', 'SequenceOfPsidGroupPermissions')), opt=True)
    _ToBeSignedCertificate_canRequestRollover = NULL(name=u'canRequestRollover', mode=MODE_TYPE, tag=(9, TAG_CONTEXT_SPEC, TAG_IMPLICIT), opt=True)
    _ToBeSignedCertificate_encryptionKey = SEQ(name=u'encryptionKey', mode=MODE_TYPE, tag=(10, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('Ieee1609Dot2BaseTypes', 'PublicEncryptionKey')), opt=True)
    _ToBeSignedCertificate_verifyKeyIndicator = CHOICE(name=u'verifyKeyIndicator', mode=MODE_TYPE, tag=(11, TAG_CONTEXT_SPEC, TAG_EXPLICIT), typeref=ASN1RefType(('Ieee1609Dot2', 'VerificationKeyIndicator')))
    ToBeSignedCertificate._cont = ASN1Dict([
        (u'id', _ToBeSignedCertificate_id),
        (u'cracaId', _ToBeSignedCertificate_cracaId),
        (u'crlSeries', _ToBeSignedCertificate_crlSeries),
        (u'validityPeriod', _ToBeSignedCertificate_validityPeriod),
        (u'region', _ToBeSignedCertificate_region),
        (u'assuranceLevel', _ToBeSignedCertificate_assuranceLevel),
        (u'appPermissions', _ToBeSignedCertificate_appPermissions),
        (u'certIssuePermissions', _ToBeSignedCertificate_certIssuePermissions),
        (u'certRequestPermissions', _ToBeSignedCertificate_certRequestPermissions),
        (u'canRequestRollover', _ToBeSignedCertificate_canRequestRollover),
        (u'encryptionKey', _ToBeSignedCertificate_encryptionKey),
        (u'verifyKeyIndicator', _ToBeSignedCertificate_verifyKeyIndicator),
        ])
    ToBeSignedCertificate._ext = []
    
    #-----< CertificateId >-----#
    CertificateId = CHOICE(name=u'CertificateId', mode=MODE_TYPE)
    _CertificateId_linkageData = SEQ(name=u'linkageData', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('Ieee1609Dot2', 'LinkageData')))
    _CertificateId_name = STR_UTF8(name=u'name', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('Ieee1609Dot2BaseTypes', 'Hostname')))
    _CertificateId_binaryId = OCT_STR(name=u'binaryId', mode=MODE_TYPE, tag=(2, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _CertificateId_binaryId._const_sz = ASN1Set(rv=[], rr=[ASN1RangeInt(lb=1, ub=64)], ev=None, er=[])
    _CertificateId_none = NULL(name=u'none', mode=MODE_TYPE, tag=(3, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    CertificateId._cont = ASN1Dict([
        (u'linkageData', _CertificateId_linkageData),
        (u'name', _CertificateId_name),
        (u'binaryId', _CertificateId_binaryId),
        (u'none', _CertificateId_none),
        ])
    CertificateId._ext = []
    
    #-----< LinkageData >-----#
    LinkageData = SEQ(name=u'LinkageData', mode=MODE_TYPE)
    _LinkageData_iCert = INT(name=u'iCert', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('Ieee1609Dot2BaseTypes', 'IValue')))
    _LinkageData_linkage_value = OCT_STR(name=u'linkage-value', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('Ieee1609Dot2BaseTypes', 'LinkageValue')))
    _LinkageData_group_linkage_value = SEQ(name=u'group-linkage-value', mode=MODE_TYPE, tag=(2, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('Ieee1609Dot2BaseTypes', 'GroupLinkageValue')), opt=True)
    LinkageData._cont = ASN1Dict([
        (u'iCert', _LinkageData_iCert),
        (u'linkage-value', _LinkageData_linkage_value),
        (u'group-linkage-value', _LinkageData_group_linkage_value),
        ])
    LinkageData._ext = None
    
    #-----< EndEntityType >-----#
    EndEntityType = BIT_STR(name=u'EndEntityType', mode=MODE_TYPE)
    EndEntityType._cont = ASN1Dict([(u'app', 0), (u'enroll', 1)])
    EndEntityType._const_sz = ASN1Set(rv=[8], rr=[], ev=None, er=[])
    
    #-----< PsidGroupPermissions >-----#
    PsidGroupPermissions = SEQ(name=u'PsidGroupPermissions', mode=MODE_TYPE)
    _PsidGroupPermissions_subjectPermissions = CHOICE(name=u'subjectPermissions', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_EXPLICIT), typeref=ASN1RefType(('Ieee1609Dot2', 'SubjectPermissions')))
    _PsidGroupPermissions_minChainLength = INT(name=u'minChainLength', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT), default=1)
    _PsidGroupPermissions_chainLengthRange = INT(name=u'chainLengthRange', mode=MODE_TYPE, tag=(2, TAG_CONTEXT_SPEC, TAG_IMPLICIT), default=0)
    _PsidGroupPermissions_eeType = BIT_STR(name=u'eeType', mode=MODE_TYPE, tag=(3, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('Ieee1609Dot2', 'EndEntityType')), default=(128, 8))
    PsidGroupPermissions._cont = ASN1Dict([
        (u'subjectPermissions', _PsidGroupPermissions_subjectPermissions),
        (u'minChainLength', _PsidGroupPermissions_minChainLength),
        (u'chainLengthRange', _PsidGroupPermissions_chainLengthRange),
        (u'eeType', _PsidGroupPermissions_eeType),
        ])
    PsidGroupPermissions._ext = None
    
    #-----< SequenceOfPsidGroupPermissions >-----#
    SequenceOfPsidGroupPermissions = SEQ_OF(name=u'SequenceOfPsidGroupPermissions', mode=MODE_TYPE)
    _SequenceOfPsidGroupPermissions__item_ = SEQ(name='_item_', mode=MODE_TYPE, typeref=ASN1RefType(('Ieee1609Dot2', 'PsidGroupPermissions')))
    SequenceOfPsidGroupPermissions._cont = _SequenceOfPsidGroupPermissions__item_
    
    #-----< SubjectPermissions >-----#
    SubjectPermissions = CHOICE(name=u'SubjectPermissions', mode=MODE_TYPE)
    _SubjectPermissions_explicit = SEQ_OF(name=u'explicit', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('Ieee1609Dot2BaseTypes', 'SequenceOfPsidSspRange')))
    _SubjectPermissions_all = NULL(name=u'all', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    SubjectPermissions._cont = ASN1Dict([
        (u'explicit', _SubjectPermissions_explicit),
        (u'all', _SubjectPermissions_all),
        ])
    SubjectPermissions._ext = []
    
    #-----< VerificationKeyIndicator >-----#
    VerificationKeyIndicator = CHOICE(name=u'VerificationKeyIndicator', mode=MODE_TYPE)
    _VerificationKeyIndicator_verificationKey = CHOICE(name=u'verificationKey', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_EXPLICIT), typeref=ASN1RefType(('Ieee1609Dot2BaseTypes', 'PublicVerificationKey')))
    _VerificationKeyIndicator_reconstructionValue = CHOICE(name=u'reconstructionValue', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_EXPLICIT), typeref=ASN1RefType(('Ieee1609Dot2BaseTypes', 'EccP256CurvePoint')))
    VerificationKeyIndicator._cont = ASN1Dict([
        (u'verificationKey', _VerificationKeyIndicator_verificationKey),
        (u'reconstructionValue', _VerificationKeyIndicator_reconstructionValue),
        ])
    VerificationKeyIndicator._ext = []
    
    _all_ = [
        _Ieee1609Dot2Data_protocolVersion,
        _Ieee1609Dot2Data_content,
        Ieee1609Dot2Data,
        _Ieee1609Dot2Content_unsecuredData,
        _Ieee1609Dot2Content_signedData,
        _Ieee1609Dot2Content_encryptedData,
        _Ieee1609Dot2Content_signedCertificateRequest,
        Ieee1609Dot2Content,
        _SignedData_hashId,
        _SignedData_tbsData,
        _SignedData_signer,
        _SignedData_signature,
        SignedData,
        _ToBeSignedData_payload,
        _ToBeSignedData_headerInfo,
        ToBeSignedData,
        _SignedDataPayload_data,
        _SignedDataPayload_extDataHash,
        SignedDataPayload,
        _HashedData_sha256HashedData,
        _HashedData_sha384HashedData,
        _HashedData_reserved,
        HashedData,
        _HeaderInfo_psid,
        _HeaderInfo_generationTime,
        _HeaderInfo_expiryTime,
        _HeaderInfo_generationLocation,
        _HeaderInfo_p2pcdLearningRequest,
        _HeaderInfo_missingCrlIdentifier,
        _HeaderInfo_encryptionKey,
        _HeaderInfo_inlineP2pcdRequest,
        _HeaderInfo_requestedCertificate,
        _HeaderInfo_pduFunctionalType,
        _HeaderInfo_contributedExtensions,
        HeaderInfo,
        _MissingCrlIdentifier_cracaId,
        _MissingCrlIdentifier_crlSeries,
        MissingCrlIdentifier,
        PduFunctionalType,
        tlsHandshake,
        iso21177ExtendedAuth,
        _ContributedExtensionBlocks__item_,
        ContributedExtensionBlocks,
        __ContributedExtensionBlock_contributorId_tab,
        ___ContributedExtensionBlock_contributorId_tab_val_Extn_0,
        _ContributedExtensionBlock_contributorId,
        __ContributedExtensionBlock_extns__item_,
        _ContributedExtensionBlock_extns,
        ContributedExtensionBlock,
        _IEEE1609DOT2_HEADERINFO_CONTRIBUTED_EXTENSION_id,
        _IEEE1609DOT2_HEADERINFO_CONTRIBUTED_EXTENSION_Extn,
        IEEE1609DOT2_HEADERINFO_CONTRIBUTED_EXTENSION,
        Ieee1609Dot2HeaderInfoContributedExtensions,
        _Ieee1609Dot2HeaderInfoContributedExtensions_val_Extn_0,
        HeaderInfoContributorId,
        etsiHeaderInfoContributorId,
        _SignerIdentifier_digest,
        _SignerIdentifier_certificate,
        _SignerIdentifier_self,
        SignerIdentifier,
        _EncryptedData_recipients,
        _EncryptedData_ciphertext,
        EncryptedData,
        _RecipientInfo_pskRecipInfo,
        _RecipientInfo_symmRecipInfo,
        _RecipientInfo_certRecipInfo,
        _RecipientInfo_signedDataRecipInfo,
        _RecipientInfo_rekRecipInfo,
        RecipientInfo,
        _SequenceOfRecipientInfo__item_,
        SequenceOfRecipientInfo,
        PreSharedKeyRecipientInfo,
        _SymmRecipientInfo_recipientId,
        _SymmRecipientInfo_encKey,
        SymmRecipientInfo,
        _PKRecipientInfo_recipientId,
        _PKRecipientInfo_encKey,
        PKRecipientInfo,
        _EncryptedDataEncryptionKey_eciesNistP256,
        _EncryptedDataEncryptionKey_eciesBrainpoolP256r1,
        EncryptedDataEncryptionKey,
        _SymmetricCiphertext_aes128ccm,
        SymmetricCiphertext,
        _AesCcmCiphertext_nonce,
        _AesCcmCiphertext_ccmCiphertext,
        AesCcmCiphertext,
        Countersignature,
        Certificate,
        _SequenceOfCertificate__item_,
        SequenceOfCertificate,
        _CertificateBase_version,
        _CertificateBase_type,
        _CertificateBase_issuer,
        _CertificateBase_toBeSigned,
        _CertificateBase_signature,
        CertificateBase,
        CertificateType,
        ImplicitCertificate,
        ExplicitCertificate,
        _IssuerIdentifier_sha256AndDigest,
        _IssuerIdentifier_self,
        _IssuerIdentifier_sha384AndDigest,
        IssuerIdentifier,
        _ToBeSignedCertificate_id,
        _ToBeSignedCertificate_cracaId,
        _ToBeSignedCertificate_crlSeries,
        _ToBeSignedCertificate_validityPeriod,
        _ToBeSignedCertificate_region,
        _ToBeSignedCertificate_assuranceLevel,
        _ToBeSignedCertificate_appPermissions,
        _ToBeSignedCertificate_certIssuePermissions,
        _ToBeSignedCertificate_certRequestPermissions,
        _ToBeSignedCertificate_canRequestRollover,
        _ToBeSignedCertificate_encryptionKey,
        _ToBeSignedCertificate_verifyKeyIndicator,
        ToBeSignedCertificate,
        _CertificateId_linkageData,
        _CertificateId_name,
        _CertificateId_binaryId,
        _CertificateId_none,
        CertificateId,
        _LinkageData_iCert,
        _LinkageData_linkage_value,
        _LinkageData_group_linkage_value,
        LinkageData,
        EndEntityType,
        _PsidGroupPermissions_subjectPermissions,
        _PsidGroupPermissions_minChainLength,
        _PsidGroupPermissions_chainLengthRange,
        _PsidGroupPermissions_eeType,
        PsidGroupPermissions,
        _SequenceOfPsidGroupPermissions__item_,
        SequenceOfPsidGroupPermissions,
        _SubjectPermissions_explicit,
        _SubjectPermissions_all,
        SubjectPermissions,
        _VerificationKeyIndicator_verificationKey,
        _VerificationKeyIndicator_reconstructionValue,
        VerificationKeyIndicator,
    ]

class Ieee1609Dot2BaseTypes:

    _name_  = u'Ieee1609Dot2BaseTypes'
    _oid_   = [1, 3, 111, 2, 1609, 2, 1, 2, 2, 2]
    
    _obj_ = [
        u'Uint3',
        u'Uint8',
        u'Uint16',
        u'Uint32',
        u'Uint64',
        u'SequenceOfUint8',
        u'SequenceOfUint16',
        u'Opaque',
        u'HashedId3',
        u'SequenceOfHashedId3',
        u'HashedId8',
        u'HashedId10',
        u'HashedId32',
        u'Time32',
        u'Time64',
        u'ValidityPeriod',
        u'Duration',
        u'GeographicRegion',
        u'CircularRegion',
        u'RectangularRegion',
        u'SequenceOfRectangularRegion',
        u'PolygonalRegion',
        u'TwoDLocation',
        u'IdentifiedRegion',
        u'SequenceOfIdentifiedRegion',
        u'CountryOnly',
        u'CountryAndRegions',
        u'CountryAndSubregions',
        u'RegionAndSubregions',
        u'SequenceOfRegionAndSubregions',
        u'ThreeDLocation',
        u'Latitude',
        u'Longitude',
        u'Elevation',
        u'NinetyDegreeInt',
        u'KnownLatitude',
        u'UnknownLatitude',
        u'OneEightyDegreeInt',
        u'KnownLongitude',
        u'UnknownLongitude',
        u'Signature',
        u'EcdsaP256Signature',
        u'EcdsaP384Signature',
        u'EccP256CurvePoint',
        u'EccP384CurvePoint',
        u'SymmAlgorithm',
        u'HashAlgorithm',
        u'EciesP256EncryptedKey',
        u'EncryptionKey',
        u'PublicEncryptionKey',
        u'BasePublicEncryptionKey',
        u'PublicVerificationKey',
        u'SymmetricEncryptionKey',
        u'PsidSsp',
        u'SequenceOfPsidSsp',
        u'Psid',
        u'SequenceOfPsid',
        u'ServiceSpecificPermissions',
        u'BitmapSsp',
        u'PsidSspRange',
        u'SequenceOfPsidSspRange',
        u'SspRange',
        u'BitmapSspRange',
        u'SequenceOfOctetString',
        u'SubjectAssurance',
        u'CrlSeries',
        u'IValue',
        u'Hostname',
        u'LinkageValue',
        u'GroupLinkageValue',
        u'LaId',
        u'LinkageSeed',
        ]
    _type_ = [
        u'Uint3',
        u'Uint8',
        u'Uint16',
        u'Uint32',
        u'Uint64',
        u'SequenceOfUint8',
        u'SequenceOfUint16',
        u'Opaque',
        u'HashedId3',
        u'SequenceOfHashedId3',
        u'HashedId8',
        u'HashedId10',
        u'HashedId32',
        u'Time32',
        u'Time64',
        u'ValidityPeriod',
        u'Duration',
        u'GeographicRegion',
        u'CircularRegion',
        u'RectangularRegion',
        u'SequenceOfRectangularRegion',
        u'PolygonalRegion',
        u'TwoDLocation',
        u'IdentifiedRegion',
        u'SequenceOfIdentifiedRegion',
        u'CountryOnly',
        u'CountryAndRegions',
        u'CountryAndSubregions',
        u'RegionAndSubregions',
        u'SequenceOfRegionAndSubregions',
        u'ThreeDLocation',
        u'Latitude',
        u'Longitude',
        u'Elevation',
        u'NinetyDegreeInt',
        u'KnownLatitude',
        u'UnknownLatitude',
        u'OneEightyDegreeInt',
        u'KnownLongitude',
        u'UnknownLongitude',
        u'Signature',
        u'EcdsaP256Signature',
        u'EcdsaP384Signature',
        u'EccP256CurvePoint',
        u'EccP384CurvePoint',
        u'SymmAlgorithm',
        u'HashAlgorithm',
        u'EciesP256EncryptedKey',
        u'EncryptionKey',
        u'PublicEncryptionKey',
        u'BasePublicEncryptionKey',
        u'PublicVerificationKey',
        u'SymmetricEncryptionKey',
        u'PsidSsp',
        u'SequenceOfPsidSsp',
        u'Psid',
        u'SequenceOfPsid',
        u'ServiceSpecificPermissions',
        u'BitmapSsp',
        u'PsidSspRange',
        u'SequenceOfPsidSspRange',
        u'SspRange',
        u'BitmapSspRange',
        u'SequenceOfOctetString',
        u'SubjectAssurance',
        u'CrlSeries',
        u'IValue',
        u'Hostname',
        u'LinkageValue',
        u'GroupLinkageValue',
        u'LaId',
        u'LinkageSeed',
        ]
    _set_ = [
        ]
    _val_ = [
        ]
    _class_ = [
        ]
    _param_ = [
        ]
    
    #-----< Uint3 >-----#
    Uint3 = INT(name=u'Uint3', mode=MODE_TYPE)
    Uint3._const_val = ASN1Set(rv=[], rr=[ASN1RangeInt(lb=0, ub=7)], ev=None, er=[])
    
    #-----< Uint8 >-----#
    Uint8 = INT(name=u'Uint8', mode=MODE_TYPE)
    Uint8._const_val = ASN1Set(rv=[], rr=[ASN1RangeInt(lb=0, ub=255)], ev=None, er=[])
    
    #-----< Uint16 >-----#
    Uint16 = INT(name=u'Uint16', mode=MODE_TYPE)
    Uint16._const_val = ASN1Set(rv=[], rr=[ASN1RangeInt(lb=0, ub=65535)], ev=None, er=[])
    
    #-----< Uint32 >-----#
    Uint32 = INT(name=u'Uint32', mode=MODE_TYPE)
    Uint32._const_val = ASN1Set(rv=[], rr=[ASN1RangeInt(lb=0, ub=4294967295)], ev=None, er=[])
    
    #-----< Uint64 >-----#
    Uint64 = INT(name=u'Uint64', mode=MODE_TYPE)
    Uint64._const_val = ASN1Set(rv=[], rr=[ASN1RangeInt(lb=0, ub=18446744073709551615)], ev=None, er=[])
    
    #-----< SequenceOfUint8 >-----#
    SequenceOfUint8 = SEQ_OF(name=u'SequenceOfUint8', mode=MODE_TYPE)
    _SequenceOfUint8__item_ = INT(name='_item_', mode=MODE_TYPE, typeref=ASN1RefType(('Ieee1609Dot2BaseTypes', 'Uint8')))
    SequenceOfUint8._cont = _SequenceOfUint8__item_
    
    #-----< SequenceOfUint16 >-----#
    SequenceOfUint16 = SEQ_OF(name=u'SequenceOfUint16', mode=MODE_TYPE)
    _SequenceOfUint16__item_ = INT(name='_item_', mode=MODE_TYPE, typeref=ASN1RefType(('Ieee1609Dot2BaseTypes', 'Uint16')))
    SequenceOfUint16._cont = _SequenceOfUint16__item_
    
    #-----< Opaque >-----#
    Opaque = OCT_STR(name=u'Opaque', mode=MODE_TYPE)
    
    #-----< HashedId3 >-----#
    HashedId3 = OCT_STR(name=u'HashedId3', mode=MODE_TYPE)
    HashedId3._const_sz = ASN1Set(rv=[3], rr=[], ev=None, er=[])
    
    #-----< SequenceOfHashedId3 >-----#
    SequenceOfHashedId3 = SEQ_OF(name=u'SequenceOfHashedId3', mode=MODE_TYPE)
    _SequenceOfHashedId3__item_ = OCT_STR(name='_item_', mode=MODE_TYPE, typeref=ASN1RefType(('Ieee1609Dot2BaseTypes', 'HashedId3')))
    SequenceOfHashedId3._cont = _SequenceOfHashedId3__item_
    
    #-----< HashedId8 >-----#
    HashedId8 = OCT_STR(name=u'HashedId8', mode=MODE_TYPE)
    HashedId8._const_sz = ASN1Set(rv=[8], rr=[], ev=None, er=[])
    
    #-----< HashedId10 >-----#
    HashedId10 = OCT_STR(name=u'HashedId10', mode=MODE_TYPE)
    HashedId10._const_sz = ASN1Set(rv=[10], rr=[], ev=None, er=[])
    
    #-----< HashedId32 >-----#
    HashedId32 = OCT_STR(name=u'HashedId32', mode=MODE_TYPE)
    HashedId32._const_sz = ASN1Set(rv=[32], rr=[], ev=None, er=[])
    
    #-----< Time32 >-----#
    Time32 = INT(name=u'Time32', mode=MODE_TYPE, typeref=ASN1RefType(('Ieee1609Dot2BaseTypes', 'Uint32')))
    
    #-----< Time64 >-----#
    Time64 = INT(name=u'Time64', mode=MODE_TYPE, typeref=ASN1RefType(('Ieee1609Dot2BaseTypes', 'Uint64')))
    
    #-----< ValidityPeriod >-----#
    ValidityPeriod = SEQ(name=u'ValidityPeriod', mode=MODE_TYPE)
    _ValidityPeriod_start = INT(name=u'start', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('Ieee1609Dot2BaseTypes', 'Time32')))
    _ValidityPeriod_duration = CHOICE(name=u'duration', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_EXPLICIT), typeref=ASN1RefType(('Ieee1609Dot2BaseTypes', 'Duration')))
    ValidityPeriod._cont = ASN1Dict([
        (u'start', _ValidityPeriod_start),
        (u'duration', _ValidityPeriod_duration),
        ])
    ValidityPeriod._ext = None
    
    #-----< Duration >-----#
    Duration = CHOICE(name=u'Duration', mode=MODE_TYPE)
    _Duration_microseconds = INT(name=u'microseconds', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('Ieee1609Dot2BaseTypes', 'Uint16')))
    _Duration_milliseconds = INT(name=u'milliseconds', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('Ieee1609Dot2BaseTypes', 'Uint16')))
    _Duration_seconds = INT(name=u'seconds', mode=MODE_TYPE, tag=(2, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('Ieee1609Dot2BaseTypes', 'Uint16')))
    _Duration_minutes = INT(name=u'minutes', mode=MODE_TYPE, tag=(3, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('Ieee1609Dot2BaseTypes', 'Uint16')))
    _Duration_hours = INT(name=u'hours', mode=MODE_TYPE, tag=(4, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('Ieee1609Dot2BaseTypes', 'Uint16')))
    _Duration_sixtyHours = INT(name=u'sixtyHours', mode=MODE_TYPE, tag=(5, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('Ieee1609Dot2BaseTypes', 'Uint16')))
    _Duration_years = INT(name=u'years', mode=MODE_TYPE, tag=(6, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('Ieee1609Dot2BaseTypes', 'Uint16')))
    Duration._cont = ASN1Dict([
        (u'microseconds', _Duration_microseconds),
        (u'milliseconds', _Duration_milliseconds),
        (u'seconds', _Duration_seconds),
        (u'minutes', _Duration_minutes),
        (u'hours', _Duration_hours),
        (u'sixtyHours', _Duration_sixtyHours),
        (u'years', _Duration_years),
        ])
    Duration._ext = None
    
    #-----< GeographicRegion >-----#
    GeographicRegion = CHOICE(name=u'GeographicRegion', mode=MODE_TYPE)
    _GeographicRegion_circularRegion = SEQ(name=u'circularRegion', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('Ieee1609Dot2BaseTypes', 'CircularRegion')))
    _GeographicRegion_rectangularRegion = SEQ_OF(name=u'rectangularRegion', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('Ieee1609Dot2BaseTypes', 'SequenceOfRectangularRegion')))
    _GeographicRegion_polygonalRegion = SEQ_OF(name=u'polygonalRegion', mode=MODE_TYPE, tag=(2, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('Ieee1609Dot2BaseTypes', 'PolygonalRegion')))
    _GeographicRegion_identifiedRegion = SEQ_OF(name=u'identifiedRegion', mode=MODE_TYPE, tag=(3, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('Ieee1609Dot2BaseTypes', 'SequenceOfIdentifiedRegion')))
    GeographicRegion._cont = ASN1Dict([
        (u'circularRegion', _GeographicRegion_circularRegion),
        (u'rectangularRegion', _GeographicRegion_rectangularRegion),
        (u'polygonalRegion', _GeographicRegion_polygonalRegion),
        (u'identifiedRegion', _GeographicRegion_identifiedRegion),
        ])
    GeographicRegion._ext = []
    
    #-----< CircularRegion >-----#
    CircularRegion = SEQ(name=u'CircularRegion', mode=MODE_TYPE)
    _CircularRegion_center = SEQ(name=u'center', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('Ieee1609Dot2BaseTypes', 'TwoDLocation')))
    _CircularRegion_radius = INT(name=u'radius', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('Ieee1609Dot2BaseTypes', 'Uint16')))
    CircularRegion._cont = ASN1Dict([
        (u'center', _CircularRegion_center),
        (u'radius', _CircularRegion_radius),
        ])
    CircularRegion._ext = None
    
    #-----< RectangularRegion >-----#
    RectangularRegion = SEQ(name=u'RectangularRegion', mode=MODE_TYPE)
    _RectangularRegion_northWest = SEQ(name=u'northWest', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('Ieee1609Dot2BaseTypes', 'TwoDLocation')))
    _RectangularRegion_southEast = SEQ(name=u'southEast', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('Ieee1609Dot2BaseTypes', 'TwoDLocation')))
    RectangularRegion._cont = ASN1Dict([
        (u'northWest', _RectangularRegion_northWest),
        (u'southEast', _RectangularRegion_southEast),
        ])
    RectangularRegion._ext = None
    
    #-----< SequenceOfRectangularRegion >-----#
    SequenceOfRectangularRegion = SEQ_OF(name=u'SequenceOfRectangularRegion', mode=MODE_TYPE)
    _SequenceOfRectangularRegion__item_ = SEQ(name='_item_', mode=MODE_TYPE, typeref=ASN1RefType(('Ieee1609Dot2BaseTypes', 'RectangularRegion')))
    SequenceOfRectangularRegion._cont = _SequenceOfRectangularRegion__item_
    
    #-----< PolygonalRegion >-----#
    PolygonalRegion = SEQ_OF(name=u'PolygonalRegion', mode=MODE_TYPE)
    _PolygonalRegion__item_ = SEQ(name='_item_', mode=MODE_TYPE, typeref=ASN1RefType(('Ieee1609Dot2BaseTypes', 'TwoDLocation')))
    PolygonalRegion._cont = _PolygonalRegion__item_
    PolygonalRegion._const_sz = ASN1Set(rv=[], rr=[ASN1RangeInt(lb=3, ub=None)], ev=None, er=[])
    
    #-----< TwoDLocation >-----#
    TwoDLocation = SEQ(name=u'TwoDLocation', mode=MODE_TYPE)
    _TwoDLocation_latitude = INT(name=u'latitude', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('Ieee1609Dot2BaseTypes', 'Latitude')))
    _TwoDLocation_longitude = INT(name=u'longitude', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('Ieee1609Dot2BaseTypes', 'Longitude')))
    TwoDLocation._cont = ASN1Dict([
        (u'latitude', _TwoDLocation_latitude),
        (u'longitude', _TwoDLocation_longitude),
        ])
    TwoDLocation._ext = None
    
    #-----< IdentifiedRegion >-----#
    IdentifiedRegion = CHOICE(name=u'IdentifiedRegion', mode=MODE_TYPE)
    _IdentifiedRegion_countryOnly = INT(name=u'countryOnly', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('Ieee1609Dot2BaseTypes', 'CountryOnly')))
    _IdentifiedRegion_countryAndRegions = SEQ(name=u'countryAndRegions', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('Ieee1609Dot2BaseTypes', 'CountryAndRegions')))
    _IdentifiedRegion_countryAndSubregions = SEQ(name=u'countryAndSubregions', mode=MODE_TYPE, tag=(2, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('Ieee1609Dot2BaseTypes', 'CountryAndSubregions')))
    IdentifiedRegion._cont = ASN1Dict([
        (u'countryOnly', _IdentifiedRegion_countryOnly),
        (u'countryAndRegions', _IdentifiedRegion_countryAndRegions),
        (u'countryAndSubregions', _IdentifiedRegion_countryAndSubregions),
        ])
    IdentifiedRegion._ext = []
    
    #-----< SequenceOfIdentifiedRegion >-----#
    SequenceOfIdentifiedRegion = SEQ_OF(name=u'SequenceOfIdentifiedRegion', mode=MODE_TYPE)
    _SequenceOfIdentifiedRegion__item_ = CHOICE(name='_item_', mode=MODE_TYPE, typeref=ASN1RefType(('Ieee1609Dot2BaseTypes', 'IdentifiedRegion')))
    SequenceOfIdentifiedRegion._cont = _SequenceOfIdentifiedRegion__item_
    
    #-----< CountryOnly >-----#
    CountryOnly = INT(name=u'CountryOnly', mode=MODE_TYPE, typeref=ASN1RefType(('Ieee1609Dot2BaseTypes', 'Uint16')))
    
    #-----< CountryAndRegions >-----#
    CountryAndRegions = SEQ(name=u'CountryAndRegions', mode=MODE_TYPE)
    _CountryAndRegions_countryOnly = INT(name=u'countryOnly', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('Ieee1609Dot2BaseTypes', 'CountryOnly')))
    _CountryAndRegions_regions = SEQ_OF(name=u'regions', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('Ieee1609Dot2BaseTypes', 'SequenceOfUint8')))
    CountryAndRegions._cont = ASN1Dict([
        (u'countryOnly', _CountryAndRegions_countryOnly),
        (u'regions', _CountryAndRegions_regions),
        ])
    CountryAndRegions._ext = None
    
    #-----< CountryAndSubregions >-----#
    CountryAndSubregions = SEQ(name=u'CountryAndSubregions', mode=MODE_TYPE)
    _CountryAndSubregions_country = INT(name=u'country', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('Ieee1609Dot2BaseTypes', 'CountryOnly')))
    _CountryAndSubregions_regionAndSubregions = SEQ_OF(name=u'regionAndSubregions', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('Ieee1609Dot2BaseTypes', 'SequenceOfRegionAndSubregions')))
    CountryAndSubregions._cont = ASN1Dict([
        (u'country', _CountryAndSubregions_country),
        (u'regionAndSubregions', _CountryAndSubregions_regionAndSubregions),
        ])
    CountryAndSubregions._ext = None
    
    #-----< RegionAndSubregions >-----#
    RegionAndSubregions = SEQ(name=u'RegionAndSubregions', mode=MODE_TYPE)
    _RegionAndSubregions_region = INT(name=u'region', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('Ieee1609Dot2BaseTypes', 'Uint8')))
    _RegionAndSubregions_subregions = SEQ_OF(name=u'subregions', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('Ieee1609Dot2BaseTypes', 'SequenceOfUint16')))
    RegionAndSubregions._cont = ASN1Dict([
        (u'region', _RegionAndSubregions_region),
        (u'subregions', _RegionAndSubregions_subregions),
        ])
    RegionAndSubregions._ext = None
    
    #-----< SequenceOfRegionAndSubregions >-----#
    SequenceOfRegionAndSubregions = SEQ_OF(name=u'SequenceOfRegionAndSubregions', mode=MODE_TYPE)
    _SequenceOfRegionAndSubregions__item_ = SEQ(name='_item_', mode=MODE_TYPE, typeref=ASN1RefType(('Ieee1609Dot2BaseTypes', 'RegionAndSubregions')))
    SequenceOfRegionAndSubregions._cont = _SequenceOfRegionAndSubregions__item_
    
    #-----< ThreeDLocation >-----#
    ThreeDLocation = SEQ(name=u'ThreeDLocation', mode=MODE_TYPE)
    _ThreeDLocation_latitude = INT(name=u'latitude', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('Ieee1609Dot2BaseTypes', 'Latitude')))
    _ThreeDLocation_longitude = INT(name=u'longitude', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('Ieee1609Dot2BaseTypes', 'Longitude')))
    _ThreeDLocation_elevation = INT(name=u'elevation', mode=MODE_TYPE, tag=(2, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('Ieee1609Dot2BaseTypes', 'Elevation')))
    ThreeDLocation._cont = ASN1Dict([
        (u'latitude', _ThreeDLocation_latitude),
        (u'longitude', _ThreeDLocation_longitude),
        (u'elevation', _ThreeDLocation_elevation),
        ])
    ThreeDLocation._ext = None
    
    #-----< Latitude >-----#
    Latitude = INT(name=u'Latitude', mode=MODE_TYPE, typeref=ASN1RefType(('Ieee1609Dot2BaseTypes', 'NinetyDegreeInt')))
    
    #-----< Longitude >-----#
    Longitude = INT(name=u'Longitude', mode=MODE_TYPE, typeref=ASN1RefType(('Ieee1609Dot2BaseTypes', 'OneEightyDegreeInt')))
    
    #-----< Elevation >-----#
    Elevation = INT(name=u'Elevation', mode=MODE_TYPE, typeref=ASN1RefType(('Ieee1609Dot2BaseTypes', 'Uint16')))
    
    #-----< NinetyDegreeInt >-----#
    NinetyDegreeInt = INT(name=u'NinetyDegreeInt', mode=MODE_TYPE)
    NinetyDegreeInt._cont = ASN1Dict([(u'min', -900000000), (u'max', 900000000), (u'unknown', 900000001)])
    NinetyDegreeInt._const_val = ASN1Set(rv=[], rr=[ASN1RangeInt(lb=-900000000, ub=900000001)], ev=None, er=[])
    
    #-----< KnownLatitude >-----#
    KnownLatitude = INT(name=u'KnownLatitude', mode=MODE_TYPE, typeref=ASN1RefType(('Ieee1609Dot2BaseTypes', 'NinetyDegreeInt')))
    KnownLatitude._const_val = ASN1Set(rv=[], rr=[ASN1RangeInt(lb=-900000000, ub=900000000)], ev=None, er=[])
    
    #-----< UnknownLatitude >-----#
    UnknownLatitude = INT(name=u'UnknownLatitude', mode=MODE_TYPE, typeref=ASN1RefType(('Ieee1609Dot2BaseTypes', 'NinetyDegreeInt')))
    UnknownLatitude._const_val = ASN1Set(rv=[900000001], rr=[], ev=None, er=[])
    
    #-----< OneEightyDegreeInt >-----#
    OneEightyDegreeInt = INT(name=u'OneEightyDegreeInt', mode=MODE_TYPE)
    OneEightyDegreeInt._cont = ASN1Dict([(u'min', -1799999999), (u'max', 1800000000), (u'unknown', 1800000001)])
    OneEightyDegreeInt._const_val = ASN1Set(rv=[], rr=[ASN1RangeInt(lb=-1799999999, ub=1800000001)], ev=None, er=[])
    
    #-----< KnownLongitude >-----#
    KnownLongitude = INT(name=u'KnownLongitude', mode=MODE_TYPE, typeref=ASN1RefType(('Ieee1609Dot2BaseTypes', 'OneEightyDegreeInt')))
    KnownLongitude._const_val = ASN1Set(rv=[], rr=[ASN1RangeInt(lb=-1799999999, ub=1800000000)], ev=None, er=[])
    
    #-----< UnknownLongitude >-----#
    UnknownLongitude = INT(name=u'UnknownLongitude', mode=MODE_TYPE, typeref=ASN1RefType(('Ieee1609Dot2BaseTypes', 'OneEightyDegreeInt')))
    UnknownLongitude._const_val = ASN1Set(rv=[1800000001], rr=[], ev=None, er=[])
    
    #-----< Signature >-----#
    Signature = CHOICE(name=u'Signature', mode=MODE_TYPE)
    _Signature_ecdsaNistP256Signature = SEQ(name=u'ecdsaNistP256Signature', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('Ieee1609Dot2BaseTypes', 'EcdsaP256Signature')))
    _Signature_ecdsaBrainpoolP256r1Signature = SEQ(name=u'ecdsaBrainpoolP256r1Signature', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('Ieee1609Dot2BaseTypes', 'EcdsaP256Signature')))
    _Signature_ecdsaBrainpoolP384r1Signature = SEQ(name=u'ecdsaBrainpoolP384r1Signature', mode=MODE_TYPE, tag=(2, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('Ieee1609Dot2BaseTypes', 'EcdsaP384Signature')))
    Signature._cont = ASN1Dict([
        (u'ecdsaNistP256Signature', _Signature_ecdsaNistP256Signature),
        (u'ecdsaBrainpoolP256r1Signature', _Signature_ecdsaBrainpoolP256r1Signature),
        (u'ecdsaBrainpoolP384r1Signature', _Signature_ecdsaBrainpoolP384r1Signature),
        ])
    Signature._ext = [u'ecdsaBrainpoolP384r1Signature']
    
    #-----< EcdsaP256Signature >-----#
    EcdsaP256Signature = SEQ(name=u'EcdsaP256Signature', mode=MODE_TYPE)
    _EcdsaP256Signature_rSig = CHOICE(name=u'rSig', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_EXPLICIT), typeref=ASN1RefType(('Ieee1609Dot2BaseTypes', 'EccP256CurvePoint')))
    _EcdsaP256Signature_sSig = OCT_STR(name=u'sSig', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _EcdsaP256Signature_sSig._const_sz = ASN1Set(rv=[32], rr=[], ev=None, er=[])
    EcdsaP256Signature._cont = ASN1Dict([
        (u'rSig', _EcdsaP256Signature_rSig),
        (u'sSig', _EcdsaP256Signature_sSig),
        ])
    EcdsaP256Signature._ext = None
    
    #-----< EcdsaP384Signature >-----#
    EcdsaP384Signature = SEQ(name=u'EcdsaP384Signature', mode=MODE_TYPE)
    _EcdsaP384Signature_rSig = CHOICE(name=u'rSig', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_EXPLICIT), typeref=ASN1RefType(('Ieee1609Dot2BaseTypes', 'EccP384CurvePoint')))
    _EcdsaP384Signature_sSig = OCT_STR(name=u'sSig', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _EcdsaP384Signature_sSig._const_sz = ASN1Set(rv=[48], rr=[], ev=None, er=[])
    EcdsaP384Signature._cont = ASN1Dict([
        (u'rSig', _EcdsaP384Signature_rSig),
        (u'sSig', _EcdsaP384Signature_sSig),
        ])
    EcdsaP384Signature._ext = None
    
    #-----< EccP256CurvePoint >-----#
    EccP256CurvePoint = CHOICE(name=u'EccP256CurvePoint', mode=MODE_TYPE)
    _EccP256CurvePoint_x_only = OCT_STR(name=u'x-only', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _EccP256CurvePoint_x_only._const_sz = ASN1Set(rv=[32], rr=[], ev=None, er=[])
    _EccP256CurvePoint_fill = NULL(name=u'fill', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _EccP256CurvePoint_compressed_y_0 = OCT_STR(name=u'compressed-y-0', mode=MODE_TYPE, tag=(2, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _EccP256CurvePoint_compressed_y_0._const_sz = ASN1Set(rv=[32], rr=[], ev=None, er=[])
    _EccP256CurvePoint_compressed_y_1 = OCT_STR(name=u'compressed-y-1', mode=MODE_TYPE, tag=(3, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _EccP256CurvePoint_compressed_y_1._const_sz = ASN1Set(rv=[32], rr=[], ev=None, er=[])
    _EccP256CurvePoint_uncompressedP256 = SEQ(name=u'uncompressedP256', mode=MODE_TYPE, tag=(4, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    __EccP256CurvePoint_uncompressedP256_x = OCT_STR(name=u'x', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    __EccP256CurvePoint_uncompressedP256_x._const_sz = ASN1Set(rv=[32], rr=[], ev=None, er=[])
    __EccP256CurvePoint_uncompressedP256_y = OCT_STR(name=u'y', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    __EccP256CurvePoint_uncompressedP256_y._const_sz = ASN1Set(rv=[32], rr=[], ev=None, er=[])
    _EccP256CurvePoint_uncompressedP256._cont = ASN1Dict([
        (u'x', __EccP256CurvePoint_uncompressedP256_x),
        (u'y', __EccP256CurvePoint_uncompressedP256_y),
        ])
    _EccP256CurvePoint_uncompressedP256._ext = None
    EccP256CurvePoint._cont = ASN1Dict([
        (u'x-only', _EccP256CurvePoint_x_only),
        (u'fill', _EccP256CurvePoint_fill),
        (u'compressed-y-0', _EccP256CurvePoint_compressed_y_0),
        (u'compressed-y-1', _EccP256CurvePoint_compressed_y_1),
        (u'uncompressedP256', _EccP256CurvePoint_uncompressedP256),
        ])
    EccP256CurvePoint._ext = None
    
    #-----< EccP384CurvePoint >-----#
    EccP384CurvePoint = CHOICE(name=u'EccP384CurvePoint', mode=MODE_TYPE)
    _EccP384CurvePoint_x_only = OCT_STR(name=u'x-only', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _EccP384CurvePoint_x_only._const_sz = ASN1Set(rv=[48], rr=[], ev=None, er=[])
    _EccP384CurvePoint_fill = NULL(name=u'fill', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _EccP384CurvePoint_compressed_y_0 = OCT_STR(name=u'compressed-y-0', mode=MODE_TYPE, tag=(2, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _EccP384CurvePoint_compressed_y_0._const_sz = ASN1Set(rv=[48], rr=[], ev=None, er=[])
    _EccP384CurvePoint_compressed_y_1 = OCT_STR(name=u'compressed-y-1', mode=MODE_TYPE, tag=(3, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _EccP384CurvePoint_compressed_y_1._const_sz = ASN1Set(rv=[48], rr=[], ev=None, er=[])
    _EccP384CurvePoint_uncompressedP384 = SEQ(name=u'uncompressedP384', mode=MODE_TYPE, tag=(4, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    __EccP384CurvePoint_uncompressedP384_x = OCT_STR(name=u'x', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    __EccP384CurvePoint_uncompressedP384_x._const_sz = ASN1Set(rv=[48], rr=[], ev=None, er=[])
    __EccP384CurvePoint_uncompressedP384_y = OCT_STR(name=u'y', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    __EccP384CurvePoint_uncompressedP384_y._const_sz = ASN1Set(rv=[48], rr=[], ev=None, er=[])
    _EccP384CurvePoint_uncompressedP384._cont = ASN1Dict([
        (u'x', __EccP384CurvePoint_uncompressedP384_x),
        (u'y', __EccP384CurvePoint_uncompressedP384_y),
        ])
    _EccP384CurvePoint_uncompressedP384._ext = None
    EccP384CurvePoint._cont = ASN1Dict([
        (u'x-only', _EccP384CurvePoint_x_only),
        (u'fill', _EccP384CurvePoint_fill),
        (u'compressed-y-0', _EccP384CurvePoint_compressed_y_0),
        (u'compressed-y-1', _EccP384CurvePoint_compressed_y_1),
        (u'uncompressedP384', _EccP384CurvePoint_uncompressedP384),
        ])
    EccP384CurvePoint._ext = None
    
    #-----< SymmAlgorithm >-----#
    SymmAlgorithm = ENUM(name=u'SymmAlgorithm', mode=MODE_TYPE)
    SymmAlgorithm._cont = ASN1Dict([(u'aes128Ccm', 0)])
    SymmAlgorithm._ext = []
    
    #-----< HashAlgorithm >-----#
    HashAlgorithm = ENUM(name=u'HashAlgorithm', mode=MODE_TYPE)
    HashAlgorithm._cont = ASN1Dict([(u'sha256', 0), (u'sha384', 1)])
    HashAlgorithm._ext = [u'sha384']
    
    #-----< EciesP256EncryptedKey >-----#
    EciesP256EncryptedKey = SEQ(name=u'EciesP256EncryptedKey', mode=MODE_TYPE)
    _EciesP256EncryptedKey_v = CHOICE(name=u'v', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_EXPLICIT), typeref=ASN1RefType(('Ieee1609Dot2BaseTypes', 'EccP256CurvePoint')))
    _EciesP256EncryptedKey_c = OCT_STR(name=u'c', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _EciesP256EncryptedKey_c._const_sz = ASN1Set(rv=[16], rr=[], ev=None, er=[])
    _EciesP256EncryptedKey_t = OCT_STR(name=u't', mode=MODE_TYPE, tag=(2, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _EciesP256EncryptedKey_t._const_sz = ASN1Set(rv=[16], rr=[], ev=None, er=[])
    EciesP256EncryptedKey._cont = ASN1Dict([
        (u'v', _EciesP256EncryptedKey_v),
        (u'c', _EciesP256EncryptedKey_c),
        (u't', _EciesP256EncryptedKey_t),
        ])
    EciesP256EncryptedKey._ext = None
    
    #-----< EncryptionKey >-----#
    EncryptionKey = CHOICE(name=u'EncryptionKey', mode=MODE_TYPE)
    _EncryptionKey_public = SEQ(name=u'public', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('Ieee1609Dot2BaseTypes', 'PublicEncryptionKey')))
    _EncryptionKey_symmetric = CHOICE(name=u'symmetric', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_EXPLICIT), typeref=ASN1RefType(('Ieee1609Dot2BaseTypes', 'SymmetricEncryptionKey')))
    EncryptionKey._cont = ASN1Dict([
        (u'public', _EncryptionKey_public),
        (u'symmetric', _EncryptionKey_symmetric),
        ])
    EncryptionKey._ext = None
    
    #-----< PublicEncryptionKey >-----#
    PublicEncryptionKey = SEQ(name=u'PublicEncryptionKey', mode=MODE_TYPE)
    _PublicEncryptionKey_supportedSymmAlg = ENUM(name=u'supportedSymmAlg', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('Ieee1609Dot2BaseTypes', 'SymmAlgorithm')))
    _PublicEncryptionKey_publicKey = CHOICE(name=u'publicKey', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_EXPLICIT), typeref=ASN1RefType(('Ieee1609Dot2BaseTypes', 'BasePublicEncryptionKey')))
    PublicEncryptionKey._cont = ASN1Dict([
        (u'supportedSymmAlg', _PublicEncryptionKey_supportedSymmAlg),
        (u'publicKey', _PublicEncryptionKey_publicKey),
        ])
    PublicEncryptionKey._ext = None
    
    #-----< BasePublicEncryptionKey >-----#
    BasePublicEncryptionKey = CHOICE(name=u'BasePublicEncryptionKey', mode=MODE_TYPE)
    _BasePublicEncryptionKey_eciesNistP256 = CHOICE(name=u'eciesNistP256', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_EXPLICIT), typeref=ASN1RefType(('Ieee1609Dot2BaseTypes', 'EccP256CurvePoint')))
    _BasePublicEncryptionKey_eciesBrainpoolP256r1 = CHOICE(name=u'eciesBrainpoolP256r1', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_EXPLICIT), typeref=ASN1RefType(('Ieee1609Dot2BaseTypes', 'EccP256CurvePoint')))
    BasePublicEncryptionKey._cont = ASN1Dict([
        (u'eciesNistP256', _BasePublicEncryptionKey_eciesNistP256),
        (u'eciesBrainpoolP256r1', _BasePublicEncryptionKey_eciesBrainpoolP256r1),
        ])
    BasePublicEncryptionKey._ext = []
    
    #-----< PublicVerificationKey >-----#
    PublicVerificationKey = CHOICE(name=u'PublicVerificationKey', mode=MODE_TYPE)
    _PublicVerificationKey_ecdsaNistP256 = CHOICE(name=u'ecdsaNistP256', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_EXPLICIT), typeref=ASN1RefType(('Ieee1609Dot2BaseTypes', 'EccP256CurvePoint')))
    _PublicVerificationKey_ecdsaBrainpoolP256r1 = CHOICE(name=u'ecdsaBrainpoolP256r1', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_EXPLICIT), typeref=ASN1RefType(('Ieee1609Dot2BaseTypes', 'EccP256CurvePoint')))
    _PublicVerificationKey_ecdsaBrainpoolP384r1 = CHOICE(name=u'ecdsaBrainpoolP384r1', mode=MODE_TYPE, tag=(2, TAG_CONTEXT_SPEC, TAG_EXPLICIT), typeref=ASN1RefType(('Ieee1609Dot2BaseTypes', 'EccP384CurvePoint')))
    PublicVerificationKey._cont = ASN1Dict([
        (u'ecdsaNistP256', _PublicVerificationKey_ecdsaNistP256),
        (u'ecdsaBrainpoolP256r1', _PublicVerificationKey_ecdsaBrainpoolP256r1),
        (u'ecdsaBrainpoolP384r1', _PublicVerificationKey_ecdsaBrainpoolP384r1),
        ])
    PublicVerificationKey._ext = [u'ecdsaBrainpoolP384r1']
    
    #-----< SymmetricEncryptionKey >-----#
    SymmetricEncryptionKey = CHOICE(name=u'SymmetricEncryptionKey', mode=MODE_TYPE)
    _SymmetricEncryptionKey_aes128Ccm = OCT_STR(name=u'aes128Ccm', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _SymmetricEncryptionKey_aes128Ccm._const_sz = ASN1Set(rv=[16], rr=[], ev=None, er=[])
    SymmetricEncryptionKey._cont = ASN1Dict([
        (u'aes128Ccm', _SymmetricEncryptionKey_aes128Ccm),
        ])
    SymmetricEncryptionKey._ext = []
    
    #-----< PsidSsp >-----#
    PsidSsp = SEQ(name=u'PsidSsp', mode=MODE_TYPE)
    _PsidSsp_psid = INT(name=u'psid', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('Ieee1609Dot2BaseTypes', 'Psid')))
    _PsidSsp_ssp = CHOICE(name=u'ssp', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_EXPLICIT), typeref=ASN1RefType(('Ieee1609Dot2BaseTypes', 'ServiceSpecificPermissions')), opt=True)
    PsidSsp._cont = ASN1Dict([
        (u'psid', _PsidSsp_psid),
        (u'ssp', _PsidSsp_ssp),
        ])
    PsidSsp._ext = None
    
    #-----< SequenceOfPsidSsp >-----#
    SequenceOfPsidSsp = SEQ_OF(name=u'SequenceOfPsidSsp', mode=MODE_TYPE)
    _SequenceOfPsidSsp__item_ = SEQ(name='_item_', mode=MODE_TYPE, typeref=ASN1RefType(('Ieee1609Dot2BaseTypes', 'PsidSsp')))
    SequenceOfPsidSsp._cont = _SequenceOfPsidSsp__item_
    
    #-----< Psid >-----#
    Psid = INT(name=u'Psid', mode=MODE_TYPE)
    Psid._const_val = ASN1Set(rv=[], rr=[ASN1RangeInt(lb=0, ub=None)], ev=None, er=[])
    
    #-----< SequenceOfPsid >-----#
    SequenceOfPsid = SEQ_OF(name=u'SequenceOfPsid', mode=MODE_TYPE)
    _SequenceOfPsid__item_ = INT(name='_item_', mode=MODE_TYPE, typeref=ASN1RefType(('Ieee1609Dot2BaseTypes', 'Psid')))
    SequenceOfPsid._cont = _SequenceOfPsid__item_
    
    #-----< ServiceSpecificPermissions >-----#
    ServiceSpecificPermissions = CHOICE(name=u'ServiceSpecificPermissions', mode=MODE_TYPE)
    _ServiceSpecificPermissions_opaque = OCT_STR(name=u'opaque', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _ServiceSpecificPermissions_opaque._const_sz = ASN1Set(rv=[], rr=[ASN1RangeInt(lb=0, ub=None)], ev=None, er=[])
    _ServiceSpecificPermissions_bitmapSsp = OCT_STR(name=u'bitmapSsp', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('Ieee1609Dot2BaseTypes', 'BitmapSsp')))
    ServiceSpecificPermissions._cont = ASN1Dict([
        (u'opaque', _ServiceSpecificPermissions_opaque),
        (u'bitmapSsp', _ServiceSpecificPermissions_bitmapSsp),
        ])
    ServiceSpecificPermissions._ext = [u'bitmapSsp']
    
    #-----< BitmapSsp >-----#
    BitmapSsp = OCT_STR(name=u'BitmapSsp', mode=MODE_TYPE)
    BitmapSsp._const_sz = ASN1Set(rv=[], rr=[ASN1RangeInt(lb=0, ub=31)], ev=None, er=[])
    
    #-----< PsidSspRange >-----#
    PsidSspRange = SEQ(name=u'PsidSspRange', mode=MODE_TYPE)
    _PsidSspRange_psid = INT(name=u'psid', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('Ieee1609Dot2BaseTypes', 'Psid')))
    _PsidSspRange_sspRange = CHOICE(name=u'sspRange', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_EXPLICIT), typeref=ASN1RefType(('Ieee1609Dot2BaseTypes', 'SspRange')), opt=True)
    PsidSspRange._cont = ASN1Dict([
        (u'psid', _PsidSspRange_psid),
        (u'sspRange', _PsidSspRange_sspRange),
        ])
    PsidSspRange._ext = None
    
    #-----< SequenceOfPsidSspRange >-----#
    SequenceOfPsidSspRange = SEQ_OF(name=u'SequenceOfPsidSspRange', mode=MODE_TYPE)
    _SequenceOfPsidSspRange__item_ = SEQ(name='_item_', mode=MODE_TYPE, typeref=ASN1RefType(('Ieee1609Dot2BaseTypes', 'PsidSspRange')))
    SequenceOfPsidSspRange._cont = _SequenceOfPsidSspRange__item_
    
    #-----< SspRange >-----#
    SspRange = CHOICE(name=u'SspRange', mode=MODE_TYPE)
    _SspRange_opaque = SEQ_OF(name=u'opaque', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('Ieee1609Dot2BaseTypes', 'SequenceOfOctetString')))
    _SspRange_all = NULL(name=u'all', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _SspRange_bitmapSspRange = SEQ(name=u'bitmapSspRange', mode=MODE_TYPE, tag=(2, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('Ieee1609Dot2BaseTypes', 'BitmapSspRange')))
    SspRange._cont = ASN1Dict([
        (u'opaque', _SspRange_opaque),
        (u'all', _SspRange_all),
        (u'bitmapSspRange', _SspRange_bitmapSspRange),
        ])
    SspRange._ext = [u'bitmapSspRange']
    
    #-----< BitmapSspRange >-----#
    BitmapSspRange = SEQ(name=u'BitmapSspRange', mode=MODE_TYPE)
    _BitmapSspRange_sspValue = OCT_STR(name=u'sspValue', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _BitmapSspRange_sspValue._const_sz = ASN1Set(rv=[], rr=[ASN1RangeInt(lb=1, ub=32)], ev=None, er=[])
    _BitmapSspRange_sspBitmask = OCT_STR(name=u'sspBitmask', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _BitmapSspRange_sspBitmask._const_sz = ASN1Set(rv=[], rr=[ASN1RangeInt(lb=1, ub=32)], ev=None, er=[])
    BitmapSspRange._cont = ASN1Dict([
        (u'sspValue', _BitmapSspRange_sspValue),
        (u'sspBitmask', _BitmapSspRange_sspBitmask),
        ])
    BitmapSspRange._ext = None
    
    #-----< SequenceOfOctetString >-----#
    SequenceOfOctetString = SEQ_OF(name=u'SequenceOfOctetString', mode=MODE_TYPE)
    _SequenceOfOctetString__item_ = OCT_STR(name='_item_', mode=MODE_TYPE)
    _SequenceOfOctetString__item_._const_sz = ASN1Set(rv=[], rr=[ASN1RangeInt(lb=0, ub=None)], ev=None, er=[])
    SequenceOfOctetString._cont = _SequenceOfOctetString__item_
    SequenceOfOctetString._const_sz = ASN1Set(rv=[], rr=[ASN1RangeInt(lb=0, ub=None)], ev=None, er=[])
    
    #-----< SubjectAssurance >-----#
    SubjectAssurance = OCT_STR(name=u'SubjectAssurance', mode=MODE_TYPE)
    SubjectAssurance._const_sz = ASN1Set(rv=[1], rr=[], ev=None, er=[])
    
    #-----< CrlSeries >-----#
    CrlSeries = INT(name=u'CrlSeries', mode=MODE_TYPE, typeref=ASN1RefType(('Ieee1609Dot2BaseTypes', 'Uint16')))
    
    #-----< IValue >-----#
    IValue = INT(name=u'IValue', mode=MODE_TYPE, typeref=ASN1RefType(('Ieee1609Dot2BaseTypes', 'Uint16')))
    
    #-----< Hostname >-----#
    Hostname = STR_UTF8(name=u'Hostname', mode=MODE_TYPE)
    Hostname._const_sz = ASN1Set(rv=[], rr=[ASN1RangeInt(lb=0, ub=255)], ev=None, er=[])
    
    #-----< LinkageValue >-----#
    LinkageValue = OCT_STR(name=u'LinkageValue', mode=MODE_TYPE)
    LinkageValue._const_sz = ASN1Set(rv=[9], rr=[], ev=None, er=[])
    
    #-----< GroupLinkageValue >-----#
    GroupLinkageValue = SEQ(name=u'GroupLinkageValue', mode=MODE_TYPE)
    _GroupLinkageValue_jValue = OCT_STR(name=u'jValue', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _GroupLinkageValue_jValue._const_sz = ASN1Set(rv=[4], rr=[], ev=None, er=[])
    _GroupLinkageValue_value = OCT_STR(name=u'value', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _GroupLinkageValue_value._const_sz = ASN1Set(rv=[9], rr=[], ev=None, er=[])
    GroupLinkageValue._cont = ASN1Dict([
        (u'jValue', _GroupLinkageValue_jValue),
        (u'value', _GroupLinkageValue_value),
        ])
    GroupLinkageValue._ext = None
    
    #-----< LaId >-----#
    LaId = OCT_STR(name=u'LaId', mode=MODE_TYPE)
    LaId._const_sz = ASN1Set(rv=[2], rr=[], ev=None, er=[])
    
    #-----< LinkageSeed >-----#
    LinkageSeed = OCT_STR(name=u'LinkageSeed', mode=MODE_TYPE)
    LinkageSeed._const_sz = ASN1Set(rv=[16], rr=[], ev=None, er=[])
    
    _all_ = [
        Uint3,
        Uint8,
        Uint16,
        Uint32,
        Uint64,
        _SequenceOfUint8__item_,
        SequenceOfUint8,
        _SequenceOfUint16__item_,
        SequenceOfUint16,
        Opaque,
        HashedId3,
        _SequenceOfHashedId3__item_,
        SequenceOfHashedId3,
        HashedId8,
        HashedId10,
        HashedId32,
        Time32,
        Time64,
        _ValidityPeriod_start,
        _ValidityPeriod_duration,
        ValidityPeriod,
        _Duration_microseconds,
        _Duration_milliseconds,
        _Duration_seconds,
        _Duration_minutes,
        _Duration_hours,
        _Duration_sixtyHours,
        _Duration_years,
        Duration,
        _GeographicRegion_circularRegion,
        _GeographicRegion_rectangularRegion,
        _GeographicRegion_polygonalRegion,
        _GeographicRegion_identifiedRegion,
        GeographicRegion,
        _CircularRegion_center,
        _CircularRegion_radius,
        CircularRegion,
        _RectangularRegion_northWest,
        _RectangularRegion_southEast,
        RectangularRegion,
        _SequenceOfRectangularRegion__item_,
        SequenceOfRectangularRegion,
        _PolygonalRegion__item_,
        PolygonalRegion,
        _TwoDLocation_latitude,
        _TwoDLocation_longitude,
        TwoDLocation,
        _IdentifiedRegion_countryOnly,
        _IdentifiedRegion_countryAndRegions,
        _IdentifiedRegion_countryAndSubregions,
        IdentifiedRegion,
        _SequenceOfIdentifiedRegion__item_,
        SequenceOfIdentifiedRegion,
        CountryOnly,
        _CountryAndRegions_countryOnly,
        _CountryAndRegions_regions,
        CountryAndRegions,
        _CountryAndSubregions_country,
        _CountryAndSubregions_regionAndSubregions,
        CountryAndSubregions,
        _RegionAndSubregions_region,
        _RegionAndSubregions_subregions,
        RegionAndSubregions,
        _SequenceOfRegionAndSubregions__item_,
        SequenceOfRegionAndSubregions,
        _ThreeDLocation_latitude,
        _ThreeDLocation_longitude,
        _ThreeDLocation_elevation,
        ThreeDLocation,
        Latitude,
        Longitude,
        Elevation,
        NinetyDegreeInt,
        KnownLatitude,
        UnknownLatitude,
        OneEightyDegreeInt,
        KnownLongitude,
        UnknownLongitude,
        _Signature_ecdsaNistP256Signature,
        _Signature_ecdsaBrainpoolP256r1Signature,
        _Signature_ecdsaBrainpoolP384r1Signature,
        Signature,
        _EcdsaP256Signature_rSig,
        _EcdsaP256Signature_sSig,
        EcdsaP256Signature,
        _EcdsaP384Signature_rSig,
        _EcdsaP384Signature_sSig,
        EcdsaP384Signature,
        _EccP256CurvePoint_x_only,
        _EccP256CurvePoint_fill,
        _EccP256CurvePoint_compressed_y_0,
        _EccP256CurvePoint_compressed_y_1,
        __EccP256CurvePoint_uncompressedP256_x,
        __EccP256CurvePoint_uncompressedP256_y,
        _EccP256CurvePoint_uncompressedP256,
        EccP256CurvePoint,
        _EccP384CurvePoint_x_only,
        _EccP384CurvePoint_fill,
        _EccP384CurvePoint_compressed_y_0,
        _EccP384CurvePoint_compressed_y_1,
        __EccP384CurvePoint_uncompressedP384_x,
        __EccP384CurvePoint_uncompressedP384_y,
        _EccP384CurvePoint_uncompressedP384,
        EccP384CurvePoint,
        SymmAlgorithm,
        HashAlgorithm,
        _EciesP256EncryptedKey_v,
        _EciesP256EncryptedKey_c,
        _EciesP256EncryptedKey_t,
        EciesP256EncryptedKey,
        _EncryptionKey_public,
        _EncryptionKey_symmetric,
        EncryptionKey,
        _PublicEncryptionKey_supportedSymmAlg,
        _PublicEncryptionKey_publicKey,
        PublicEncryptionKey,
        _BasePublicEncryptionKey_eciesNistP256,
        _BasePublicEncryptionKey_eciesBrainpoolP256r1,
        BasePublicEncryptionKey,
        _PublicVerificationKey_ecdsaNistP256,
        _PublicVerificationKey_ecdsaBrainpoolP256r1,
        _PublicVerificationKey_ecdsaBrainpoolP384r1,
        PublicVerificationKey,
        _SymmetricEncryptionKey_aes128Ccm,
        SymmetricEncryptionKey,
        _PsidSsp_psid,
        _PsidSsp_ssp,
        PsidSsp,
        _SequenceOfPsidSsp__item_,
        SequenceOfPsidSsp,
        Psid,
        _SequenceOfPsid__item_,
        SequenceOfPsid,
        _ServiceSpecificPermissions_opaque,
        _ServiceSpecificPermissions_bitmapSsp,
        ServiceSpecificPermissions,
        BitmapSsp,
        _PsidSspRange_psid,
        _PsidSspRange_sspRange,
        PsidSspRange,
        _SequenceOfPsidSspRange__item_,
        SequenceOfPsidSspRange,
        _SspRange_opaque,
        _SspRange_all,
        _SspRange_bitmapSspRange,
        SspRange,
        _BitmapSspRange_sspValue,
        _BitmapSspRange_sspBitmask,
        BitmapSspRange,
        _SequenceOfOctetString__item_,
        SequenceOfOctetString,
        SubjectAssurance,
        CrlSeries,
        IValue,
        Hostname,
        LinkageValue,
        _GroupLinkageValue_jValue,
        _GroupLinkageValue_value,
        GroupLinkageValue,
        LaId,
        LinkageSeed,
    ]

init_modules(EtsiTs103097ExtensionModule, Ieee1609Dot2, Ieee1609Dot2BaseTypes)
